### ISSUE TITLE
create fixed reading line functionality

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#10]
Manager should be able to create a fixed reading line. That way all readers will have the annotations along the same axis.

Integrate security, only Manager roles can set this property (specific permission)
Database change: add extra property to line.

**Comment by JCoadDavies** [comment]
Having a length measurement of this "fixed reading line" in the output would be useful

**Comment by wimallegaert** [comment]
Fixed reading line integrated in SmartDots
Only annotations containing a line (and no dots) can be set as "fixed reading line".

The boolean property "UserCanPin" can be set on analysis level . This must  be handled in Web API. Default value = False.
