### ISSUE TITLE
It would be also very useful to have the current year’s list of stock coordinators/AWG chairs/Data compilation and or benchmark chairs, and their contact details on smartdots. (suggested by gnichonchuir)

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#103]
Carlos will investigate if there is a file already existing that can be linked

**Comment by kbekaert** [comment]
Link to SID to be inserted on the smartdots webapplication page

**Comment by cmspinto** [comment]
If this information is accessible from an ICES database then it can be put in a page in the manage area of SmartDots (to respect the GDBR).

**Comment by JCoadDavies** [comment]
The list requires annual update (on ACOM site) and is not prepared for 2020. Not sure if the dcworkshop chairs are included in the list. Needs further investigation.

**Comment by kbekaert** [comment]
Exchange and workshop reports should be sent to the WGBIOP support person to be sent to the relevant stock assessors. Not possible to provide a list of all stock assessors.
