### ISSUE TITLE
Guidelines for workshops and exchanges – a link on the front page to the pdf of guidelines for the coordinator

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#105]
Suggested by JaneGodiksen

The guidelines are being given a major update (to be ready after BIOP 2019) but the current files are here 
 http://www.ices.dk/community/Pages/PGCCDBS-doc-repository.aspx
and a link is needed on the SmartDots page

**Comment by neil-ices-dk** [comment]
Happy to do, could you just clarify if you really want a generic link or do you want specifically a link to 
1) guideline for WK's age reading/exchanges and 
2) guideline on maturity staging

_Assuming that the overall final plan is move these into the publications library as guidelines so we can then have one link to all related content for guidelines (like we do already)_

**Comment by JCoadDavies** [comment]
Once the guidelines are updated at WGBIOP I think a generic link to the data quality assurance repository would be fine. We may have had this on the SmartDots landing page before…?

Can you please post the existing link to all guideline related content?

**Comment by neil-ices-dk** [comment]
ok done.

![image](https://user-images.githubusercontent.com/23527005/63998653-e04c1880-cb01-11e9-9e75-20600fc15397.png)
