### ISSUE TITLE
Event coordinator running an event

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#106]
If an event co-ordinator is also a reader in the event then they can see the other readers annotations

**Comment by cmspinto** [comment]
The solution would be to give the permission to that user to manage the event before the event starts and remove that permission while the the user is going to complete the annotation task. 

![image](https://user-images.githubusercontent.com/8705477/52642764-ed921480-2edb-11e9-8ce6-33d7cc1008d2.png)

**Comment by kbekaert** [comment]
Added in manual on page 9 on 14/10.
