### ISSUE TITLE
Country managers should have access to all annotations of an event once the event is closed?

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#109]
When an event manager have a smartuser in an event, then they have access to that event and to the annotations of their users. 

Should they have access to the annotations of the smartusers from other countries once the event is closed?

**Comment by JCoadDavies** [comment]
Yes, i think so. Once readers have finalised their readings and an event is closed then it should  be possible to see (only see) other readers annotations (aswell as your own) and without the event report being published. This is what was needed today for event 201 where the event was closed and a skype meeting was held to discuss the readings and i needed to see how my readers annotations compared to the other readers from the other countries.
