### ISSUE TITLE
On screen measuring

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#111]
The annotation line is defined only by the corrdinaator for each workshop. It would be useful for the reader to be able to measure distances during a reading. This would be helpful to distinguish possible false rings.

**Comment by JCoadDavies** [comment]
**'1/** Measuring tool
  + Integrate a measuring tool in the image toolbar
  + The user select the measuring tool. The user clicks in the image, a line is shown, when he clicks again the length of the line will be shown in a popup (cfr scale popup)
  + Depending on the availability of the scale, the distance will be shown in pixels and in mm 
  + The measured data wan't be stored in the software
**2/** Statusbar: integrate distance between the dots 
  + If the user hovers over a dot, the age of the selected dot is shown in the statusbar
  + This information will be extended with distance information:
    □ Distance from the selected dot to the nucleus
    □ Distance to the previous dot
  + Depending on the availability of the scale, the distance will be shown in pixels and in mm 
  + The measured data wan't be stored in the software
Question: If a line exists out of multiple line segments, how should the distance be calculated? The distance be calculated along the line or as the shortest distance to the  nucleus. It's possible that none of these options will be represent the reality.
**3/** Growth graph 
  + Integration of the measurement information in the growth graph
  + The existing graph will be replaced by a more extended version: an x- and y axe will be shown
  + If the user hovers over a dot, the age of the selected dot is shown 
  + This information will be extended with distance information:
    □ Distance from the selected dot to the nucleus
    □ Distance to the previous dot
  + Depending on the availability of the scale, the distance will be shown in pixels and in mm 
The measured data wan't be stored in the software

**Comment by JCoadDavies** [comment]
Estimated cost in hours by ILVO for each option 1-3
Option 1: 8h
Option 2: 4h
Option 3 20h

**Comment by wimallegaert** [comment]
I think there will be no impact for the Web API. This is only new functionality in the software.

**Comment by JCoadDavies** [comment]
WGSMART agreed to go for option 1
If time allows in May then ILVO will implement this

**Comment by kevinatilvo** [comment]
Made a slight change as to how it is described

> The user select the measuring tool. The user clicks in the image, a line is shown, when he clicks again the length of the line will be shown in a popup (cfr scale popup)

There will be no popup, and the line length will be shown as you are making the line. This way it is more user friendly.

**Comment by kevinatilvo** [comment]
A new button with options has been added to the age-reading window.  With this button the user can measure distances on the otolith image.
Measurements will appear as a dashed colored line with text above or below it. The line width and font size are as displayed when the image is viewed on 100% size. The user can modify the measure settings.
 
![image](https://user-images.githubusercontent.com/25780423/57923700-4d190b00-78a3-11e9-8445-7239184be047.png)

To start measuring click on the Icon (left hand side) and draw a line on the image as you would make an annotation line. As you are drawing the line, the length of it is displayed along with it in pixels (if the scale is not known)  or in metric lengths (if the scale is known). 
![image](https://user-images.githubusercontent.com/25780423/57923707-51ddbf00-78a3-11e9-8217-057fd05fc387.png)
![image](https://user-images.githubusercontent.com/25780423/57923714-56a27300-78a3-11e9-89f0-98dedb05e16f.png)

Measurings can only contain 1 line segment. You can draw as many measuring lines as wished. The measuring line settings will be remembered between sessions, however measuring lines are temporary and are thus not saved.
 
![image](https://user-images.githubusercontent.com/25780423/57923721-5c985400-78a3-11e9-8665-693043eb4d04.png)
