### ISSUE TITLE
generic annotation properties

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#113]
Add extra functionality in SmartDots to manage additional annotation properties in a generic way. Extra annotation properties can be added dynamically to the annotation list and popup in SmartDots. Each property could be defined by: name, datatype (boolean, int, text, look-up list, ...), required or not, sequence;

With this functionality new annotation properties could be integrated in Smartdots without changes to the software. Only the Web API has to be extended.

Further analysis needed at first new annotation property request.
Discussed at WGSMART Meeting April 25th in relation with #76

**Comment by JCoadDavies** [comment]
This to be discussed after implementing the new properties to be released September 2019
