### ISSUE TITLE
List of maturity stagers

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#114]
I am missing a list for maturity stagers. As it is now, one has to add the maturity stagers in the same list as the age readers, and it is not possible to state that this is for maturity only. The expertise level might be different and the reading method is definitely different. 

This should be given a priority 1 and Carlos should be responsible.
Carlos, can you suggest an effort time for this?

**Comment by JCoadDavies** [comment]
We need to know if the preparation method "gonad" is sufficient. Needs to be decided up at BIOP and passed onto WGSMART

**Comment by JCoadDavies** [comment]
The downloadable list just needs to be filtered
