### ISSUE TITLE
National coordinators with different responsibility

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#115]
I am included as a coordinator without species, so I get all emails. If I wanted to add species to my expertice to let people know which species I am coordinating, I will also need to add stock ID and preparation method. This will give a lot of lines and wrong information, as I have no expertice. 
If it is possible to NOT include more info than species, if you are registering as coordinator, then this could maybe easily be solved. Age readers should always be registered with expertise level and method etc.

This should be given a Priority 2 or 3 maybe?
Responsible Carlos?

**Comment by wimallegaert** [comment]
so for stock coordinators specify only species (no stock, no prep method information)

**Comment by JCoadDavies** [comment]
Carlos to make it possible to have ONLY species defined for co-ordinators
Karen to update manual accordingly

**Comment by JaneGodiksen** [comment]
It was my suggestion, and I see now that with this opportunity, we risk that coordinators add readers without adding species. I don't know if this is a real issue. 
It might also be too much to add another level under Expertise - "Not reading" or "coordinator" or "totally incompetent" :), though it would make some kind of sense.

**Comment by JCoadDavies** [comment]
We will need to come back to this when the new script is in place - agreed at Q1

**Comment by kbekaert** [comment]
Coordinators should set up for each species. Expertise level still needed. Add in web application manual.

**Comment by cmspinto** [comment]
Will check this, might need a teams call to see this bug, sorry!

**Comment by JCoadDavies** [comment]
This happens when a user is added without a Sample Type. Carlos will make it mandatory to add Sample Type before Expertise level
