### ISSUE TITLE
Picture format

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#116]
Hope all is well. Can I please point something to you and hopefully it can be sorted easily. The image grabbing system we have in Ireland takes pictures in 16:9 format. As I uploaded them to smartdots they show perfectly but as I go into individual picture on ‘view event’ on ICES/Smartdots website they seemed to be compressed sideways as if the system squeezes them to 4:3 format. Please see below .
This is the case for images for Fish ID: PLE_001 to PLE_171.. I am just worrying that can be an issue for the report.
Could you please let me know if anything can be done to sort it out.
Many thanks
Marcin

![image](https://user-images.githubusercontent.com/8705477/59358055-317f1400-8d2c-11e9-833c-83e1992fd440.png)

**Comment by JCoadDavies** [comment]
This does not cause a problem for the report. The webinterface just needs to be "fixed" so that it can deal with images taken in different formats.

**Comment by JaneGodiksen** [comment]
This is not a big issue. It is only visible in the thumbnails, not on the images when opened fully.
