### ISSUE TITLE
Order of the event list

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#117]
In the events,  When I want to order the List of Events by start (or end date) it will order by month but not in chronological order. Surely it should be chronological…?

https://smartdots.ices.dk/manage/ManageEvent

**Comment by kevinatilvo** [comment]
Hi Carlos,
In my case it ordered by day.
You are right, it should be chronological. However,
The List of Events is 'stupid', as it does not know what fields to expect or their datatypes. That is why it sees every property as a string value. It  will also order dates as strings, not as actual dates.

The quickest fix for your issue would be to pass the DateTime as a string in the format yyyy/MM/dd.
Something like this= datetime.ToString("yyyy/MM/dd");
That way, the string notation order will always be chronological.

**Comment by kbekaert** [comment]
Tested it. It's ok.
