### ISSUE TITLE
Including age reader and maturity stager coordinators in the automatic email notification sent from SmartDots when an event is ready

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#119]

**Comment by JCoadDavies** [comment]
![image](https://user-images.githubusercontent.com/26571227/63762876-e3f25c00-c8c3-11e9-8668-d70720513b04.png)

 Add the age reader coordinators of the participants here

**Comment by cmspinto** [comment]
The email is now being sent to participants, delegates and organizers. In both the age reading events and maturity!

**Comment by JCoadDavies** [comment]
requires further testing
@kbekaert 
@AnnelieH

**Comment by JCoadDavies** [comment]
@cmspinto
