### ISSUE TITLE
Set scale of image (= relationship between pixel ratio and actual measure)

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#12]
= relationship between pixel ratio and actual measure)
2 methods: 
- Auto detection via image analysis
- Mark scale manually (by clicking on scale-line)
User must be able to set the unit: 1 mm or 0,5 mm.

Database changes: add image scale property to file

**Comment by wimallegaert** [comment]
Scale functionality integrated in SmartDots:
- Automatic scale measure
- Manual scale measure
- Delete scale

**Comment by cmspinto** [comment]
Done
