### ISSUE TITLE
Integrate sample info in file frame to sort/filter images on these properties

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#121]
The possibility to sort images using the sample info. e.g. by area, SD, catch date? Readers will often choose to read the samples from Q1 first, then Q2 and so on...

**Comment by wimallegaert** [comment]
integrating sample properties in the file frame:
- catch month, in format MMYYYY
- ices area
 -ices subdivision (for baltic see)

**Comment by wimallegaert** [comment]
Feedback ILVO:
- The sample properties are dynamic. 
- The existing web method GetFiles can be used for this. The desired sample properties can be added in the Web API. SmartDots should be extented to visualize these extra properties.
