### ISSUE TITLE
Maturity event coordinator should be able to give a stage to an image

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#123]
The maturity event coordinator should also be able to give a stage to an image because a "true age" should be given by the coordinator when there are histology samples included in the event. This isn't possible so far.

**Comment by cmspinto** [comment]
Has a event manager the users will be able to browse the fish and will have a link to do an annotation: 

![image](https://user-images.githubusercontent.com/8705477/64698399-1ba3fb00-d4a3-11e9-8c5c-3db3a64f6f91.png)

**Comment by kbekaert** [comment]
tested on 14/10. Was able to stage in dab event on maturity. So OK.
