### ISSUE TITLE
maturity: once the event is closed, stagers should be able to see results from others

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#125]
create the possibility that readers can see the stages given by other readers once the event is closed.

**Comment by cmspinto** [comment]
Done, user will be able to see how many annotations there are and the details of each annotation: 

![image](https://user-images.githubusercontent.com/8705477/64698279-e13a5e00-d4a2-11e9-979c-bed8dadf47f2.png)

**Comment by kbekaert** [comment]
tested on 14/10. Is ok.
