### ISSUE TITLE
Maturity discussion platform (feedback from Cristina Follesa)

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#126]
In my opinion in order to standardize the interpretation of the ICES Macroscale, it is important that the different readers have the opportunity ( when the exchange is closed) to see the interpretation of the other  readers involved in the exchange . Anyway, I think  that It could be also  important to have the possibility to discuss among the readers about the different interpretations ( like an exchange of ideas) .  For example, a reader can have the possibility  ( if they want) to ask to a specific reader  involved why he interpreted a specific photo as a specific macro stage for example  the stage “immature"" And the reader consulted can answered on the base his interpretation ( I.e. I saw the presence of a great number of basophils  in the histological photo) why he has  interpreted the stage as immature. I think that it could be important not to change the interpretations of the exchange ( the exchange is closed)  but  to better standardize the interpretation of the scale for future exchanges. So the idea is to  have for a determined time  ( i.e. for a week after the exchange)  a sort of interative platform in order to better understand the different interpretations. I’m not a technician so I don’t know if it can  be activate in SMARTDOTs but I think that it could be useful.

**Comment by kbekaert** [comment]
Once an event is closed, the coordinator needs to write some comments about why the stage was assigned based on the histological preparation. THis should go into the manual.

**Comment by cmspinto** [comment]
Is this tow issues, publishing the maturity events and make them available for everyone that is login?

**Comment by Follesac** [comment]
Hi Carlos,
excuse me for the delay in answering. In my opinion , in a exchange it should be important, to pubblish the maturity results make them available to everyone that is login. Then it could be usefult that the maturity readers of the exchange have the possbility to discuss the results for a limited period ( a week?) after the exchange 

Maria Cristina Follesa 
Professore Associato in Zoologia
Dipartimento di Scienze della Vita e dell’Ambiente
Università di Cagliari - Italia
telefono +39 07076758014 
fax +39 0706758022

**Comment by JCoadDavies** [comment]
@Follesac Is the current setup where stagers can view the results satisfactory OR do we need a solution?

**Comment by JCoadDavies** [comment]
Mail from 10/05/2021

Hi Julie,
regarding the response to the comment on issue 126, I think that the current setup is satisfactory. It is important to start an exchange as soon as possible in order to have the opportunity to try it.
Cheer
Cristina
