### ISSUE TITLE
Maturity (fresh/frozen) by Cristina Follesa

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#127]
In the maturity exchange, I suggest to insert a voice "frozen/ not frozen "in the macro picture because, for some species, the aspect of the gonads changes if they are frozen or not.

**Comment by kbekaert** [comment]
Add fresh or frozen to the preparation method for gonads

**Comment by JCoadDavies** [comment]
needs further investigation - need to check what is a preparation method and what is a pre-treatment method and this will tie in with the integration of the BIOP materials and methods table data into the SmartDots database for maturity

**Comment by JCoadDavies** [comment]
@cmspinto Vocab for SAMPLE TYPE needs to be GONAD_FRESH and GONAD-FROZEN.

**Comment by JCoadDavies** [comment]
Will be addressed in the suggestions from WGBIOP ToR b - updated vocabs for preparation methods

**Comment by JCoadDavies** [comment]
#188
