### ISSUE TITLE
feedback page - WGBIOP

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#134]
Making feedback page more obvious

**Comment by wimallegaert** [comment]
change name of button: feedback (instead of contact)
see feedback document on sharepoint

**Comment by JCoadDavies** [comment]
missing @neil-ices-dk to change this

**Comment by neil-ices-dk** [comment]
this one?

![image](https://user-images.githubusercontent.com/23527005/68843709-ded5c980-06c8-11ea-839e-a6f775f9188c.png)

**Comment by neil-ices-dk** [comment]
d-done :)
