### ISSUE TITLE
SmartDots@home - WGBIOP

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#137]
SmartDots@home: as the SmartDots age reading platform is an open source solution, the platform can also be used to manage internal age reading data. A custom web API and database must be developed to use the platform internally within an institute.

**Comment by kbekaert** [comment]
Write out to ICES members to see if they would be interested in the solution of working/storing data in the cloud.

**Comment by JaneGodiksen** [comment]
Questionare sent out and generic version is not feasible due to insitute specicfic requirements.
