### ISSUE TITLE
Graph frame: show multiple growth lines

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#140]
comment from Kélig

Need to develop growth line (lower left corner)  to compar different annotations by the same reader - the growth line as it is is not usefule. It is of course important that the reader cannot get info of the other readers.

**Comment by wimallegaert** [comment]
the growth line is read-only (not interactive).
We have a look how complex it is
We also look to integrate the dots in the grpah

**Comment by wimallegaert** [comment]
It would be good, for the workshop, when we open the annotations of many people, to see on one same graph the different growth patterns (feedback via Marcin Blazkowski)
