### ISSUE TITLE
Separate age reader coordinators from maturity coordinators in webAPI - WGBIOP

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#142]

**Comment by kbekaert** [comment]
Add column "Is country coordinator for maturity" and  "Is country coordinator for maturity"

**Comment by JCoadDavies** [comment]
https://smartdots.ices.dk/admin/ListOperations
This can be done in the admin page - Julie, Carlos and Karen to do

**Comment by JCoadDavies** [comment]
Carlos will do for maturity now - Julie to send contacts file

**Comment by cmspinto** [comment]
Have updated but there were some that were not found in the ICES user list. 
Have sent that list to Karen and Julie.
