### ISSUE TITLE
Difficulties due to different birthdays - 1st. July

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#145]
This can be problematic as Smartdots assigns age using a count of annotations on the winterrings.

We need to have this clarified by someone who works with a Mediterranean species

Including text from another issue on the same #202 which will be closed.
Being able to change the birthday date in the software. Currently SmartDots automatically give the age of the fish based on the number of ring annotations that you make; this implies that SmartDots already has a pre-established birthday date (1st of January). This has been a problem in the case of the anchovy from Mediterranean area (birthday on 1st of July) and it was necessary to leave the last winter ring unmarked so that the automatic age determination agreed with the one corresponding with birthday date on July 1

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
Who can take the lead on this? Someone working with Mediterranean species; Patricia? Christina? Can we go out of WGSMART?

**Comment by JaneGodiksen** [comment]
Need more information. What are the consequences? 
Megrim exchange running now. Problem here? Sardine? When they are comparing Med vs Atl.
It will be the best if just readers are given clear instructions of how to annotate in those specific situation.

**Comment by JaneGodiksen** [comment]
Need to go into the WGBIOP report from ToR f. Communication to coordinators.

**Comment by JCoadDavies** [comment]
We need to clearly communicate this to the coordinators of events of the relevant stocks

**Comment by JaneGodiksen** [comment]
Should also be included in the manual

**Comment by wimallegaert** [comment]
Since release 2.2 (2020/Q3) extra properties can be integrated in the SmartDots file frame. An extra property for the birthdate (1/1 or 1/7) could be added in the web app. This property can then be shown in the file frame.
Could the use of the parameter OSR instead of OWR be another solution?

**Comment by AnnelieH** [comment]
Can add to the manual when decided which way to go, adding birth date as an extra property or not.

**Comment by JCoadDavies** [comment]
https://github.com/ices-eg/SmartDots/issues/202
https://github.com/ices-eg/SmartDots/issues/96
https://github.com/ices-eg/SmartDots/issues/202

**Comment by JCoadDavies** [comment]
Q1 meeting 2022 "This should be added to both manuals that a coordinator should inform the readers of the birthday of the fish and that the amount of dots will be the age"
