### ISSUE TITLE
File frame: do not count fixed reading line annotations in number of annotations

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#151]
All annotations are count in the number property in the file frame. Annotations with only a fixed reading line are not really usefull to count.

Proposal: remove the the fixed reading annotations in the

**Comment by JCoadDavies** [comment]
@cmspinto 
Release notes from Kevin "Note to Web API developers: Please make sure that in your query you do not count the fixed reading
lines when assigning the total number of annotations."
