### ISSUE TITLE
organize workshop for reporting

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#154]
- how should it be organized?
- who should organize?
- who should be invited? (age coordinators, stock assessment people)
- should it include training for coordinators

**Comment by JaneGodiksen** [comment]
I miss some details here. What is the purpose of the workshop? To evaluate the report format? To develop the report further? Or is it a training workshop?

**Comment by kbekaert** [comment]
@JaneGodiksen, Hi Jane, this is exactly what should be decided. The workshop was an idea which was launched during WGSMART 2019 (don't remember by whom). First it was foreseen as a training workshop for readers and a part on reporting. Then we decided to put effort in the video tutorials for the readers. For the reporting part, we did not discuss further until now.

**Comment by JCoadDavies** [comment]
I think we should aim for this is 2021. Focus on evaluating the current statistical analysis and report based on end-user input (event coordinators AND stock assessors - we need their participation) aim to develop the report further. Plus plan how to have the report output integrated with other systems within ICES (e.g. TAF and RDBES) so that it is actually useful.

**Comment by JaneGodiksen** [comment]
To be discussion during the Nov meeting

**Comment by JaneGodiksen** [comment]
We will plan for a workshop on report output development to happen most likely in April 2021 (online)
-	 We will have to target stock assessment and modellers and ask for participation
-	Need to consider a common workshop for age and maturity
-	A two day workshop
-	Alfonso will chair the workshop along with someone who has the experience in analyzing the exchanges, Karen
-	Julie to set up a meeting in early new year to plan further and agree on what is needed.
