### ISSUE TITLE
Error message in software needs clarification

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#159]
Feedback received/reported as a bug on October 31st " When I try to save annotation I get this messages Error Saving Annotations ERROR, USER THAT IS DELITING THE ANNOTATION IS NOT THE OWNER OF THE ANNOTATION. I am trying to age read Dab exchange 2019a. best regards Audur"

**Comment by JCoadDavies** [comment]
This happens when a coordinator wants to annotate. It is written in the manual that a coordinator needs the role of reader before annotating
Carlos and Wim to figure this out.

**Comment by JCoadDavies** [comment]
The easiest way could be to change the error message "As a delegate/coordinator it is not possible to annotate. Please contact the admin to temporarily change your role for this event" Carlos to test this

**Comment by cmspinto** [comment]
Message has changed to: ERROR: As a delegate/coordinator it is not possible to annotate. Please contact the admin to temporarily change your role for this event.

Needs testing!
