### ISSUE TITLE
What should be the domain:

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#16]
otolithes.ices.dk or smartdots.ices.dk or agereading.ices.dk

for now we have:

2 votes on: smartdots.ices.dk (Line and Julie)
1 vote on: agereading.ices.dk (carlos)

**Comment by neil-ices-dk** [comment]
i think we haven't done a good job here of setting the scene; will the domain be hosting the international version of smartdots - in which case the vote would be for smartdots.ices.dk, but if the domain is intended to have a wider use and functionality this may not be the obvious domain. In the first instance, if the central tool is the focus of this then i'd go with SmartDots

**Comment by wimallegaert** [comment]
I agree, i think we can start with smartdots.ices.dk.
