### ISSUE TITLE
Solve Errors with lubridate::date function

### ISSUE THREAD

**Issue by alfonsoperezrodriguez** [ices-eg/SmartDots#166]
Sometimes you can get error message when running lubridate::year, lubridate::quarter and lubridate::month within the data_processing.R code. 
Understand why this is happening (Collin?) and if there is need to develope a two options function where this function is applied with or without seconds :%S.

**Comment by colinpmillar** [comment]
HI alfonso - do you have an example where this fails? Is it always related to having seconds in the time stamp?

**Comment by alfonsoperezrodriguez** [comment]
Hi Collin,

This is a problem that I had during the WGSMART meeting, but after I did not get it again. However, now Patricia is having that problem again, and for her this function only works when she deletes the seconds. However lubridate::date works fine for me with seconds. so this is a problem that we don´t identify the origin of the problem. May it be due tu incompatibilities between the libraries in use?

Thanks,
Alfonso.
________________________________
De: Colin Millar <notifications@github.com>
Enviado: lunes, 13 de enero de 2020 10:46
Para: ices-eg/SmartDots <SmartDots@noreply.github.com>
Cc: alfonsoperezrodriguez <fonsilei@hotmail.com>; Assign <assign@noreply.github.com>
Asunto: Re: [ices-eg/SmartDots] Solve Errors with lubridate::date function (#166)


HI alfonso - do you have an example where this fails? Is it always related to having seconds in the time stamp?

**Comment by colinpmillar** [comment]
It could be - or might be related to sytem locale... either way it seems like we should make it more robust.  It would be good if you were able to recreate the bug @gonpatricia, so we can test any potential solution :)
Cheers,
Colin

**Comment by gonpatricia** [comment]
Hi Colin,

I get this warning when I run line 39 function from data_processing.R:
> ad <-
+   within(ad, {
+     year = lubridate::year(parse_date_time(catch_date, '%d/%m/%Y %H:%M:%S'))
+     qtr = lubridate::quarter(parse_date_time(catch_date, '%d/%m/%Y %H:%M:%S'))
+     month = lubridate::month(parse_date_time(catch_date, '%d/%m/%Y %H:%M:%S'))
+   })
Warning messages:
1: All formats failed to parse. No formats found. 
2: All formats failed to parse. No formats found. 
3: All formats failed to parse. No formats found. 

> ad  ### No month, qrt and year data has been filled in, as is shown above:
...... 
  AQ_Score month qtr year
1       AQ1    NA  NA   NA
2       AQ1    NA  NA   NA
3       AQ1    NA  NA   NA
4       AQ1    NA  NA   NA
5       AQ2    NA  NA   NA

But it works well when I do not consider the %S in the format.

Thanks,
All the best,
Patrícia

**Comment by colinpmillar** [comment]
Thanks Patrícia - i'll take a look tomorrow

**Comment by gonpatricia** [comment]
This was solved!
