### ISSUE TITLE
Water type (for salmon freshwater ring and sea water rings).

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#17]
Develop extra functionality: users must be able to select different types of dots. Possible dot types are sea water (default), fresh water, .... In the user interface every type is shown by a different symbol (eg filled or open circle) 

Other properties of a dot are: color, with and symbol set (= dot or cross)

**Comment by wimallegaert** [comment]
Seawater (default) and freshwater integrated in SmartDots

**Comment by JCoadDavies** [comment]
Hi Wim. Should this issue be closed now OR is this something for Carlos to implement in the database?

**Comment by wimallegaert** [comment]
Hi Julie, this functionality is complete in the SmartDots software, i'm not sure about the integration in the Ices API.
@cmspinto: can you confirm if this functionality is integrated in your Web API?
