### ISSUE TITLE
An AQ code is needed before annotation can be approved.

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#170]
Input WMR (Loes Bolle)

There is an existing SmartDots settings RequireAQ1ForApproval. When this setting is activated only annotations with an AQ1 code can be approved.
When this setting isn't activated all annotations can be approved, even annotations without an AQ code. Is this desirable? Wouldn't it be better that an annotation only can be approved when an AQ code is present?

As an alternative solution an extra setting RequireAQForApproval could be integrated in SmartDots. When this setting is activated then an annotation only can be approved when an AQ code is present.

**Comment by JCoadDavies** [comment]
Yes it would be better that an annotation only can be approved when an AQ code is present?
Currently the AQ codes are not used in the report but are in the data download.

**Comment by JaneGodiksen** [comment]
Milestone: End of 2020? 
Assign: Carlos

**Comment by wimallegaert** [comment]
Show a popup with an info message if the user navigate to another image or create another annotation and the existing annotation is incomplete (no AQ code or not approved
