### ISSUE TITLE
Add additional dot type for false rings

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#174]
Input Ifremer Kelig Mahe (cfr TNPC)

Add an additional dot type to make a distinction between false and good rings

**Comment by JaneGodiksen** [comment]
Wouldn't that risk making it much more confusing for the readers? And if  ring doesn't have a dot, it means it is not a true ring, one shouldn't need to add a dot to state that, I think. 
I would think this is something to be included in the comment field? I assume this is interesting mostly for the workshops when the readers discuss their decisions. It is hard to remember why one took one decision and not another.

**Comment by JCoadDavies** [comment]
We think that adding dots for false rings willl be very confusing and the comment box should be used for such instances with a refernce to the specific numbered annotation.

**Comment by JaneGodiksen** [comment]
Feature will be included from issue 94
