### ISSUE TITLE
Pass a default parameter via API 

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#181]
Input WMR (Loes Bolle)

In SmartDots the user can set a parameter (eg OWR, OSR, ...) for each annotation. The list of parameters is handled via the API. If there is only parameter in the list, the parameter will be automatically selected for each new annotation. If there are multiple parameters the user has to select a parameter himself.

It would be an added value if a default value for the parameter can be set via the Web API.

**Comment by JCoadDavies** [comment]
This could potentially be added for the coordinator to provide but not the readers.
It would be good to know if there is an actual need for this - should be taken up by WGBIOP (Tor f) when the list of feedback and issues dealt with are summarised.

**Comment by JCoadDavies** [comment]
@cmspinto @wimallegaert 
Am I right that the default is OWR? If so then can we close this??

**Comment by wimallegaert** [comment]
@cmspinto some additional questions, what is the functionality in the web app?

- Can a parameter (OWR, OSR, ..) be set per event or is there only one default parameter available (OWR) for all events?
- If yes, can you add more than one parameter per event and is it possible to make one these the default one?

**Comment by JCoadDavies** [comment]
This is a little old but is relevant now with the new modules
@cmspinto see questions above - can you please answer? :-)

**Comment by cmspinto** [comment]
Need some more info about OWR, OSR. Currently none of the parameters are being passed to the software. 
I don't think this is either setup in the event, could we talk about this in WGSMART?

**Comment by JCoadDavies** [comment]
OWR = Otolith Winter Ring
OSR = Otolith Summer Ring (I have never know this to be used in SmartDots - or what countries are using it for what species?)

My reference to the new modules is because I guess we will need to add e.g. larvae, gonad, eggs or something more specific for each

Lets's talk about it on the 8th

**Comment by kbekaert** [comment]
discuss at next meeting
