### ISSUE TITLE
Gonad preparation methods to be added to ICES vocab

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#185]
Based on Cindy's suggestions 
Extra preparation methods to be added to https://vocab.ices.dk/?ref=1395
•	Histology in paraffin stained with H&E
•	Histology in resin stained with H&E
•	Histology in paraffin 
•	Histology in resin
•	Histology in paraffin stained with Toluidine Blue
•	Histology in resin stained with Toluidine Blue
•	Trichrome in paraffin stained with H&E
•	Trichrome in resin stained with H&E

Are there any special steps need to be taken when adding these OR is it straight forward as we are not changing any of the codes?

**Comment by JaneGodiksen** [comment]
The link leads to "Otolith reading quality grading". Am I correct when what is asked for is new choices in //vocab.ices.dk/?ref=1511 which are preparation methods?

**Comment by JCoadDavies** [comment]
yes, my mistake

**Comment by odontaster** [comment]
I think we can add them directly. Do you have suggestions for the codes? 
@cmspinto is there a limit of characters for this codes?

**Comment by odontaster** [comment]
done
//vocab.ices.dk/?ref=1511
