### ISSUE TITLE
Maturity scale update in the SampleUploadFile

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#186]
Sorry, i forgot to mention this one at the meeting - comment from Cindy 
"There is still the M6 scale in the SmartDotsSampleFile Excel template, that should be changed to the SMSF scale and maturity stages accordingly"

**Comment by JCoadDavies** [comment]
@CindyvanDamme  can you please follow up to make sure it is updated

**Comment by JaneGodiksen** [comment]
What is the status?
Milestone?

**Comment by CindyvanDamme** [comment]
Still not the correct scale in the SampleUploadFile, should MSMF instead of M6

**Comment by JCoadDavies** [comment]
And also to include the letters
e.g. 
A. Immature
