### ISSUE TITLE
A button to create a list of event participant emails which can be copied and pasted in an email “To: ” field.

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#187]
This would give more flexibility compared to the button that exists now on the EDIT EVENT page which will only send a mail informing readers that they are included in an event.
It is very often the case that the coordinator needs to contact the readers multiple times during the coordination of an event.

**Comment by JCoadDavies** [comment]
Julie and Carlos have discussed
@cmspinto Can you do this for our SmartDots release 2020/09 milestone?

**Comment by JaneGodiksen** [comment]
Assignees: Carlos
Milestone: Release? Or end of 2020?

**Comment by JCoadDavies** [comment]
@cmspinto This still needs to be done

**Comment by cmspinto** [comment]
It's done but not put in production, it will be available when the changes to the age readers expertise are finished.
