### ISSUE TITLE
Draft a guidance document on how to use management console for coordinators: insert your Age Readers experts, Setup and Manage a new Event

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#19]

**Comment by JCoadDavies** [comment]
Hi!
It was decided that the age reader co-ordinators who will attend WGBIOP should be those who are sent instructions on how to "insert your age readers experts" into SmartDots prior to WGBIOP. So, I have made a short document, see attached file which gives instructions on how to do this but not how to "Setup and manage a new event" as we have not reached the point of testing the upload of images and data yet. 
It is a simple document but I have made some comments in there,  sorry Carlos that I did not mention them before but it is only now when I write the instructions that these things become more obvious to me. All suggestions and comments welcome.
Do we have an official logo that could be used? It would make it look more "official" ;-)
[Inserting your age readers into SmartDots.docx](https://github.com/ices-eg/SmartDots/files/1282536/Inserting.your.age.readers.into.SmartDots.docx)

**Comment by wimallegaert** [comment]
Hi Julie,

Here is the "official" smartdots logo.

![smartdots](https://user-images.githubusercontent.com/13795097/30148444-c2b09dce-93a3-11e7-82a2-fba4214d0239.png)

**Comment by JCoadDavies** [comment]
Thanks for that Wim....better late than never :-)
All of this is now included in the ICES Web Application Manual so we can close this issue.

**Comment by JaneGodiksen** [comment]
This needs to be updated regularly.

**Comment by JCoadDavies** [comment]
This is ongoing
