### ISSUE TITLE
chosing readers/stagers in an event

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#190]
When adding readers/stagers to an event, it is sometimes difficult to know the name from the email address and thus to know who you should add. Moreover, you cannot see if the readers/stagers are in the list for maturity or age reading (now, some are in twice, with different level of expertise, you don't see if it's for age reading or maturity) 
![stagers-readers in an event](https://user-images.githubusercontent.com/25844933/86109957-3e041500-bac5-11ea-84d9-9a6ad9b01ef7.PNG)

**Comment by JaneGodiksen** [comment]
Suggestion for meeting 07.09.20: 
Assign: Carlos
Lables: Pri 1
Milestone: ASAP

I think this is important. The names of the participants are good to have. And maturity/age are extremely important.

**Comment by JaneGodiksen** [comment]
The Smart Username can be added. ICES don't have names of people.
New column with sample type.

**Comment by cmspinto** [comment]
Need a help, in what page of the webApp is this issue?

**Comment by JCoadDavies** [comment]
The edit event page - so when you are adding readers to an event

**Comment by JCoadDavies** [comment]
@cmspinto This still needs to be done

**Comment by cmspinto** [comment]
We don't have the name of the readers in SmartDots sorry.

**Comment by kbekaert** [comment]
@cmspinto, there is a second issue here that we cannot see if the experience relates to age or maturity. We need a column sample type so we know what to pick for maturity or age.

**Comment by cmspinto** [comment]
Solved the User name added to the table:

![image](https://user-images.githubusercontent.com/8705477/187620999-b945b7ef-02fc-47c8-bc97-bc5801c3e588.png)


About the Age or Maturity, that can only be solved after issue #188  is solved.

**Comment by JCoadDavies** [comment]
I think something went wrong when you did this. I tried to add a reader to ID450 yesterday by clicking on the little green "add user" button, it told me the "user has been successfully added to the event" BUT they had not been added. To add the user I needed to enter the email address of the user in the box

**Comment by cmspinto** [comment]
Have a small comment here, have included Sample Type and Preparation method in the list of the Age readers for that species. 
But shouldn't we filter for **sample type = otoliths or scales** in the edit event page of the **age reading** and filter for **Sample Type = Gonads** in the edit page of the **maturity**?

![image](https://user-images.githubusercontent.com/8705477/188407971-05414448-a300-48d4-9408-18372ab0340d.png)

**Comment by kbekaert** [comment]
> Have a small comment here, have included Sample Type and Preparation method in the list of the Age readers for that species. But shouldn't we filter for **sample type = otoliths or scales** in the edit event page of the **age reading** and filter for **Sample Type = Gonads** in the edit page of the **maturity**?
> 
> ![image](https://user-images.githubusercontent.com/8705477/188407971-05414448-a300-48d4-9408-18372ab0340d.png)

Hi @cmspinto, scales and otoliths are sometimes used in the same event, so I guess this would not be possible anymore when you filter for sample type on the "edit event" page? However, what would be really good is that when you choose "age reading" in "purpose of the event", you only get age readers (and not maturity stagers) in the list of age readers.  Is that a possibility?

**Comment by JCoadDavies** [comment]
@cmspinto 
I tested again in ID 449 with User Lundgaard and the same issue arose
