### ISSUE TITLE
Minimum criteria for publishing training events

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#192]
We need to discuss what the minimum requirements are for publishing a training event.
What defines a training event?
Do we need to add another type of event e.g reader calibration?

**Comment by JaneGodiksen** [comment]
To be discussed at WGSMART 08. Sep 2020

**Comment by JaneGodiksen** [comment]
Notes from meeting 08.Sep
-	Criteria for publishing training events?
Training events should be published when more than one country is included. As soon as the results are interesting for the stock assessors. 
Sweden have training events with Finland, they are not being published. What is the aim of the training? If it is just testing how the readers are doing, it might not be necessary to publish, but as soon as the results will have an effect on assessment, then it should be. There will be training events for both age, maturity, egg and larvae. 
Come up with a list of training events that need to be upgraded to exchanges by meeting October 23.
Criteria for publishing. 
-	Training WK?
BIOP suggested a report training workshop and we would evaluate the YouTube tutorials and how successful they are. Should it be a workshop to train people in making reports? Should it be evaluating the report?

**Comment by JCoadDavies** [comment]
[SmartDots training events Sept 2020.xlsx](https://github.com/ices-eg/SmartDots/files/5427884/SmartDots.training.events.Sept.2020.xlsx)

Of the replies received to date no "training" events should be upgraded

**Comment by JCoadDavies** [comment]
The final suggestion will be written by WGSMART and sent to WGBIOP chairs

**Comment by JCoadDavies** [comment]
Included in the January 2021 newsletter

**Comment by JCoadDavies** [comment]
I think we can close this
