### ISSUE TITLE
WGBIOP request to improve the page for Manage Events and Users

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#193]
Attached is a list of suggested improvements from WGBIOP ToR b 
[Suggestions for WGSMART Tor b. WGBIOP 2020.docx](https://github.com/ices-eg/SmartDots/files/4877990/Suggestions.for.WGSMART.Tor.b.WGBIOP.2020.docx)

**Comment by JaneGodiksen** [comment]
Suggestion for meeting 07.09.20: 
This document are referring to: Smartdots>>manage event and users >>List of age readers expertise
The last point is missing in the document.

Point 1: I agree that the stock or area column can be difficult, and we have talked about having a map available. I think a map would be better than starting to have area mentioned as "Bay of Biscay" etc. That will induce errors. (pri 1, as this is would be very helpful and save prople time and errors)
Why two identical columns? 

Point 2-6: 
I don't see a problem with extra columns, one don't have to use them. Is it a problem? (pri 3) 


Lables:
Assign:

**Comment by JaneGodiksen** [comment]
Related to #194 
Carlos will clear one column

**Comment by cmspinto** [comment]
Sorry, I'm a bit lost on what is the task here? 

Is it to put the link to a map with the ICES areas?

**Comment by JCoadDavies** [comment]
It is a little confusing.
Point 1 - suggestion is to provide a map showing the ICES and Med areas. This is to help the national coordinators define their readers/stagers expertise on the setup used expertise page

The need for a link to SID is somewhat different  #194  The SID is mostly relevant for those setting up exchanges and workshops but not specifically related to user expertise. A link somewhere in SmartDots is needed - I suggest the SmartDots landing page. Is this possible Carlos?

**Comment by JCoadDavies** [comment]
I think we need to redo the setup user expertise page once it is updated with the new parameters for the reader ranking link to 
https://github.com/ices-eg/SmartDots/issues/194

**Comment by JCoadDavies** [comment]
Are these 2 links updated and ready to allow country coordinators to enter their reader
 info needed to work with the script?

![image](https://user-images.githubusercontent.com/26571227/187410602-2991f004-1bae-47d0-a2e1-712fa318d2e2.png)

**Comment by cmspinto** [comment]
Sorry, don't understand the issue here, might need a bit more of description in these items. 

I think we can improve the labels of the links, in these case the labels are customized for Age reading but the expertise is currently also being used by the maturity community.
