### ISSUE TITLE
Link to the SID on the Setup User Expertise page

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#194]
Feedback from WGBIOP Tor B
When adding expertise to a new user it would be very useful to have more information on the list of stocks. Would it be possible to add a link here to the SID

**Comment by JaneGodiksen** [comment]
Suggestion for meeting 07.09.20: 
Assign: Carlos
Lables: age reading, web application, Pri 2
Milestone:

**Comment by JCoadDavies** [comment]
I think we need to redo the setup user expertise page once it is updated with the new parameters for the reader ranking/modal age calculation

**Comment by JCoadDavies** [comment]
linked to 
#188 

Need to talk about on 8th Sept meeting

**Comment by kbekaert** [comment]
@cmspinto ask Neil to put a link in the Smartdots homepage for SID

**Comment by cmspinto** [comment]
Put a link to SID  in the smartdots homepage: [https://www.ices.dk/data/tools/Pages/smartdots.aspx](https://www.ices.dk/data/tools/Pages/smartdots.aspx)


![image](https://user-images.githubusercontent.com/8705477/189293542-aeaf509b-c874-4a5d-a295-64cfb877ece2.png)

**Comment by neil-ices-dk** [comment]
@kbekaert i have added the link, however i would suggest you think about splitting the links into more than one menu as it is getting quite long;
![image](https://user-images.githubusercontent.com/23527005/189302382-a5838d63-f5f5-47d3-8c90-810602a87efd.png)

and example of what i mean here:
![image](https://user-images.githubusercontent.com/23527005/189302524-e41e5e93-4f00-458b-8c5b-8ec33cdb92b0.png)
