### ISSUE TITLE
Modification to Type of Event

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#195]
Feedback from WGBIOP ToR b

Under Propose a new event "To be endorsed" it is not very intuitive. A suggestion for improvement would be
Workshop (to be endorsed)
Exchange (to be endorsed)

**Comment by JaneGodiksen** [comment]
Suggestion for meeting 07.09.20: 
Assign: Carlos
Lables: age reading, web application, Pri 2
Milestone:

**Comment by JCoadDavies** [comment]
@cmspinto this still needs to be done

**Comment by cmspinto** [comment]
Done :)

![image](https://user-images.githubusercontent.com/8705477/132862456-7be5c22b-c63d-40a0-ac62-20562869907a.png)


[Event form](https://smartdots.ices.dk/manage/EventForm)
