### ISSUE TITLE
Should it be coded that readers can only approve 1 annotation per sample

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#196]
Currently, readers are instructed to approve only 1 annotation per sample (at least in some cases) BUT readers can approve multiple annotations per sample. Only 1 can be used in the analysis. Do we need to add a restriction so that we do NOT have a problem with multiple approved annotations?

**Comment by JaneGodiksen** [comment]
Yes, that sounds reasonable. I can't come up with a situation where several approved ages should be possible.

**Comment by JCoadDavies** [comment]
I just noticed i missed a VERY important "NOT" in the sentence above which i have now added!

I agree with Jane that this restriction should be added.

**Comment by JaneGodiksen** [comment]
Milestone: End of 2020?
Asignees: Carlos/Wim/Kevin ? 
Web API / Web applic.

Also relevant for maturity?

**Comment by JaneGodiksen** [comment]
It should be mentioned in the manual that if a reader has one approved annotation, and approve another one, the first approval will be un-approved.

**Comment by AnnelieH** [comment]
Added to manual.
