### ISSUE TITLE
Download csv of chosen readings 

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#199]
Being able to download a csv file for your own or all readings or raw data. 
(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
Should the raw data of all readers be downloadable for everyone participating in the exchange? I don't think so. I think it is reasonable that the reader can download her/his own readings, but only the national coordinator should have access to the readings of all the readings from ones country. And only the exchange coordinator should have access to download all readings from an exchange.
I don't know who proposed this request, but feedback from WGSMART should be given to the right people - and maybe to everyone?

**Comment by JCoadDavies** [comment]
We have spoken about this before.
It is the responsibility of the national coordinator to pass this information/data onto their readers. The national coordinator can contact the event coordinator for the data after the event has been analysed.

This can be added as a point in the next newsletter

**Comment by JCoadDavies** [comment]
We can make an option here to download county specific readers data. This will be available once the event is closed and only for your country

![image](https://user-images.githubusercontent.com/26571227/96994799-7aa0c400-152d-11eb-9f10-e3cb1178e389.png)

**Comment by cmspinto** [comment]
Done, country managers can now download the annotations only for their readers. 

I have also implemented the same as in Maturity where the Role of the user is in the message:

![image](https://user-images.githubusercontent.com/8705477/97708951-da611700-1ab9-11eb-9e69-4c7fbd5bf0a2.png)


or for the case of the country coordinator:

![image](https://user-images.githubusercontent.com/8705477/97709045-04b2d480-1aba-11eb-9b25-83e876c8a5ee.png)

**Comment by cmspinto** [comment]
Improve changing the text of the download
![image](https://user-images.githubusercontent.com/8705477/97877544-a5ed9500-1d1d-11eb-9633-2a86c123326d.png)
