### ISSUE TITLE
Report template

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#200]
Update the report template section (check of the text and include a conclusions and Outlook section)
(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
I don't understand the question. Julie?

**Comment by JCoadDavies** [comment]
There are quite a few "typos" and pieces of text in the report that need to be corrected. The attached was sent to Alfonso in January 2020.

[SmartDots_Report_Event_200_SS_NoAQ3_julie.docx](https://github.com/ices-eg/SmartDots/files/5415837/SmartDots_Report_Event_200_SS_NoAQ3_julie.docx)

A conclusion section is part of the report template. I suggest adding a sentence underneath the "Conclusions" heading "Special focus should be on highlighting lessons learned and what is needed in future exchanges/workshops."

**Comment by gonpatricia** [comment]
This has already been reviewed.
