### ISSUE TITLE
Flexible results extraction

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#201]
Flexible results extraction, depending on the needs of each stock and that can be obtained directly by the administrator / coordinator of the exchange / calibration / workshop

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
I am uncertain what is possible and what is needed. We need to have standardised reports with some flexibility. 
This should be discussed at both WGSMART and WGBIOP. Not something we can add a milestone to at the moment, I think.

**Comment by JCoadDavies** [comment]
i agree

**Comment by JCoadDavies** [comment]
#154

**Comment by JaneGodiksen** [comment]
Can we close this? It is rather flexible. But it also needs to be standardised in some way. I think it is ok as it is and maybe people just need to know the possibilities.
