### ISSUE TITLE
Birthday 1 of January

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#202]
Being able to change the birthday date in the software. Currently SmartDots automatically give the age of the fish based on the number of ring annotations that you make; this implies that SmartDots already has a pre-established birthday date (1st of January). This has been a problem in the case of the anchovy from Mediterranean area  (birthday on 1st of July) and it was necessary to leave the last winter ring unmarked so that the automatic age determination agreed with the one corresponding with birthday date on July 1

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
See issues #96 and #145 
This has been discussed at WGBIOP 2020 ToR f.

**Comment by JCoadDavies** [comment]
We have given #96 Priority 2

**Comment by JaneGodiksen** [comment]
Closing issue after including it into #145
