### ISSUE TITLE
Fixing reading line should be updated in manual

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#203]
Procedure for fixing the reading line is not very clear in the manual when setting up exchanges 

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
This should be checked. This is probalby from before latest update. Has it been changed now?

**Comment by AnnelieH** [comment]
I have not been involved in updating the manual for setting up events (Karen did it I think), only the user manual.

**Comment by JCoadDavies** [comment]
No need to update the manual now. Just remember for later.
We agreed on twice per year so then the next will be with the new release in March 2021

**Comment by JCoadDavies** [comment]
@kbekaert Can you please remember this in the next manual update
