### ISSUE TITLE
Issue with many users

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#204]
Software stopped working and recording when used by multiple users at the same time 

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
I don't know how many users took part in this event. Bug?

**Comment by JCoadDavies** [comment]
we need to know how many participants were trying to use during this event?
A stress test is needed eg. 40 people/robots. can be automated

**Comment by JaneGodiksen** [comment]
Stress test issue #212
