### ISSUE TITLE
Issue for Scallop exchange

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#206]
For Scallop exchange: Physical samples need to accompany the images as the images are not high definition enough to read, difficult to see the edge of the shell  

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
This is not relevant for WGSMART or SmartDots. This should be adressed to the coordinators of the exchange.

**Comment by JCoadDavies** [comment]
Then i think we should not even have it here as an issue
