### ISSUE TITLE
Choice of stratum

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#207]
It is desirable to have the possibility of choosing quarter as stratum, i.e. to include quarter in the data file. In that way, separate modal ages could be calculated for fish caught in different quarters, or “difficult” quarters, or quarters with limited data could be excluded, for example.

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
This needs to be discussed at WGSMART. I am a bit uncertain if this is needed, or it would be more appropriate to find another solution for this issue.

**Comment by JCoadDavies** [comment]
I think this is worth discussing.

**Comment by JaneGodiksen** [comment]
This should be included in the Workshop (#210 ?) It is too complicated for the manual.
Carlos can add more choices in the strata-drop down menu? Julie will check it in an age event.

**Comment by JaneGodiksen** [comment]
Done!
