### ISSUE TITLE
Next button for maturity events

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#208]
When doing the maturity event a "next button" would be good. As it was now when you approved one it jumped to the beginning of the page and you had to scroll down again to find where you were. 

(From WGBIOP report)

**Comment by JaneGodiksen** [comment]
Seems like a good and necessary solution. 
Milestone next release
Time?
Responsible person: Carlos, Wim?
Pri 1

**Comment by JCoadDavies** [comment]
@cmspinto Is this fixed? I cannot see it but I think you changed it??
