### ISSUE TITLE
Some kind of error

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#209]
a number of files that gave an error message when saving annotations "An explicit value for the identity column in table ‘dbo.tblLines’ can only be specified when column list is used and IDENTITY INSERT is ON."  *When you open your picture file the red square to the left goes green even though you havn’t done any annotations, it is supposed to turn green when you have saved you annotations.

(From WGBIOP report)

**Comment by JCoadDavies** [comment]
This was before the new release in sept 2020 so maybe it is solved now

**Comment by cmspinto** [comment]
Have checked this and cannot reproduce the error!

Will have to park this one to see if it happens again!
