### ISSUE TITLE
Module overview

### ISSUE THREAD

**Issue by elstorreele** [ices-eg/SmartDots#21]

**Comment by wimallegaert** [comment]
![smartdots modules](https://user-images.githubusercontent.com/13795097/27590852-417b3146-5b50-11e7-8447-6c1f007aa648.PNG)

**Comment by neil-ices-dk** [comment]
work in progress
[Software License Agreement to SMARTDOTS - DRAFT.docx](https://github.com/ices-eg/SmartDots/files/1122338/Software.License.Agreement.to.SMARTDOTS.-.DRAFT.docx)
