### ISSUE TITLE
Workshop national coordinators

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#210]

**Comment by JCoadDavies** [comment]
The suggestion from Helen at WGBIOP to hold short online training courses where the coordinators join and follow instructions and can ask questions needs to be discussed at the November 23rd meeting

**Comment by JaneGodiksen** [comment]
We need to agree on the setup for the workshop. What is needed? Who to attend? How to do it? etc etc

**Comment by JaneGodiksen** [comment]
Notes from meeting November 2020
Online training session for coordinators. One online session which is being recorded and published on Youtube. 
-	We need a list of sessions needed. Need to consider age, maturity and eggs and larva separately. Setting up an exchange, taking out the report, analysing the results, Karen and Annelie will make the list. Deadline end of January so we can plan further at Feb WebEX
-	People outside this group can make the training sessions, they just need experience with setting up an exchange. We need a defined script, set of steps to run it smoothly. Everyone needs to be able to do the same things at the same time (we need to check that SmartDots can handle that many users at the same time). We need help from ICES with the recording and WebEx setup. We need a sample and dataset for everyone to use  
-	Need to consider participants consent and privacy issues

**Comment by JCoadDavies** [comment]
By recording the tutorial session at BIOP this has been done. Once we have edited and posted on YouTube we can close this issue.

**Comment by JaneGodiksen** [comment]
Done during WGBIOP
