### ISSUE TITLE
Integration of updated R-script

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#211]
Alfonso, Colin, Joana needs to ensure the format of the R-code is in agreement with WebApp

**Comment by JCoadDavies** [comment]
pcrjoana has vanished from our github project and i cannot find her and add again?

**Comment by cmspinto** [comment]
The smartdots administrators can now run the development R script in any event.

![image](https://user-images.githubusercontent.com/8705477/104105060-f64c1a80-52ab-11eb-8181-7901b19ccf70.png)


This needs testing.

**Comment by cmspinto** [comment]
This is after the user clicks

![image](https://user-images.githubusercontent.com/8705477/104105099-40350080-52ac-11eb-8a05-c2037e779629.png)

**Comment by JCoadDavies** [comment]
The document here needs to be checked as some typos still exist https://github.com/ices-eg/SmartDots/issues/200  
The one I know for sure is "A reader rank is also assigned..."
