### ISSUE TITLE
Adding another strata option

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#213]
Adding another strata option in the drop down box - quarter; quarter and area

**Comment by cmspinto** [comment]
Need to be tested but the option will be there once the webSiteApp is updated: 

![image](https://user-images.githubusercontent.com/8705477/97410584-8a3e5500-18ff-11eb-818e-38b87cbb29b2.png)

**Comment by kbekaert** [comment]
The option is there and the strata is updated. At the moment no report for area code and quarter.
