### ISSUE TITLE
Finish Larvae Events Type

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#215]
- [x] SmartUser name in the image is not correct.
- [x] Myotomes are not showing in the image for the coordinator.
- [x] Remove coordinators from the sent email of Larvae.
- [x] Show a message saying the email has been sent, so that the user does not press again!
- [x] Make the download of the data from Larvae available.
- [x] Apply edit layout of Maturity to the Larvae (with table of annotations).
- [x] Make summary annotation Per Larvae Reader available in a link.

**Comment by cmspinto** [comment]
Need to test the message, it is suppose to be showing a message after sending the email:

![image](https://user-images.githubusercontent.com/8705477/97879959-dedb3900-1d20-11eb-9ec3-bd0f31d2ff37.png)

**Comment by cmspinto** [comment]
Layout of a table is now available:

![image](https://user-images.githubusercontent.com/8705477/98097179-f33c4480-1e8c-11eb-9d72-28448a0a6f5d.png)

**Comment by cmspinto** [comment]
Download is now working:

![image](https://user-images.githubusercontent.com/8705477/98097285-1b2ba800-1e8d-11eb-8b90-b520714cf91f.png)

**Comment by kbekaert** [comment]
@CindyvanDamme, can you test this issue so that we can close it?

**Comment by CindyvanDamme** [comment]
Tested, data download is working
