### ISSUE TITLE
Manual for eggs and larvae

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#229]
Matthias Kloppmann: 
-The manual mostly deal with age reading. Is it planned to have something similar for fish eggs and larvae?

**Comment by JaneGodiksen** [comment]
Manual will be done before the software is out. 
Until then a YouTube video could be enough. YouTube needed by?

**Comment by JCoadDavies** [comment]
Need to wait until new module is developed

**Comment by CindyvanDamme** [comment]
This is now finished with the publication of the new handbooks at https://ices-library.figshare.com/search?q=%3Atitle%3A%20smartdots&sortBy=publication_date&sortType=desc&groups=37194
