### ISSUE TITLE
Technical adjustments SmartDots: integration Web API methods

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#23]
- Integration interface SmartDots - web API 
	- Conversion fat client into thin client
	- Replacing entity framework with Web API methods
	- Optimization model / classes
	- Optimization data calls (merge)
	- Handling error messages
- Removing ILVO business rules
- Integration settings
	- show / hide properties (eg sample status, annotation isapproved)
	- enable / disable actions (eg browse, attach, detach)
- Integration read-only options
	- on file level: all linked annotations
	- on annotation level
- Sample properties
	- dynamic list of key/value pairs
- Development 2 new screens
	- Screen 1: login + web API selection
	- Screen 2: list with analysis / activities
		- Dynamic columns
		- Future functionality: offline agereading

![smartdots screen1 login](https://user-images.githubusercontent.com/13795097/27590597-7bff7c2e-5b4f-11e7-91b0-ef0f3a8f021e.png)
![smartdots screen2 analyses](https://user-images.githubusercontent.com/13795097/27590600-7e63d0fa-5b4f-11e7-98f0-01ec92bd9d5e.png)
![smartdots screen3 agereading](https://user-images.githubusercontent.com/13795097/27590604-80642af8-5b4f-11e7-9d01-5499d0112a45.png)

**Comment by neil-ices-dk** [comment]
offline age reading moved to separate issue

**Comment by neil-ices-dk** [comment]
[Smartdots Web API documentation.pdf](https://github.com/ices-eg/SmartDots/files/1256384/Smartdots.Web.API.documentation.pdf)
