### ISSUE TITLE
Develop publishing part of larvae module #228

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#230]

**Comment by cmspinto** [comment]
[Results SmartDots event 295 Internal Wageningen Marine Research training.pdf](https://github.com/ices-eg/SmartDots/files/7098011/Results.SmartDots.event.295.Internal.Wageningen.Marine.Research.training.pdf)


Report of the event

**Comment by JaneGodiksen** [comment]
Annelie bring to WGBIOP
