### ISSUE TITLE
Confusing assigning age or number of rings

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#237]
For some people (like me), there might be a confusion if they have to assign the right age, or if they have to identify the right number of rings (which can result in a different number than the estimated age). 
Maybe a clear explanatory figure or a statement at the beginning ("how do I correctly mark rings in Smartdots so that I provide age estimates that are comparable with others?") could avoid such confusion.
(Uwe Krumme)

**Comment by JaneGodiksen** [comment]
Could be useful to have a pop up box when the event coordinator sets up an event with “things to remember” or “there is a new version of the manual available”

**Comment by wimallegaert** [comment]
We can add an “?” icon in the header of the annotations frame with some additional essential info and a reference to the page in the manual. The option ‘non-counting’ mark was therefore added.

**Comment by AnnelieH** [comment]
Maybe also solved when dealing with #239 , making the explanation more clear and visible in the manual.

**Comment by JaneGodiksen** [comment]
Look to #239 Annelie updates the manual. This issue gets closed now.
