### ISSUE TITLE
Dealing with increments not yet formed

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#239]
I had some problems with marking the increments which are not formed yet. For Baltic sprat, the birthday is 1st of January. In the exchange, the otoliths from the 1st and 2nd quarters were used. In most of the cases, the winter ring did not appear yet. In that situation, I have marked the last increment at the edge of the otolith but in my opinion, it is not correct. And when I looked at the results I have noticed that some of them were not counted by SamrtDots. As a coordinator of the event, I know also that one of the participants in the pictures of otolith for 1Q and 2Q did not mark the last year at all. I could not find any information in the manual on how to mark the increment which is not formed yet. The problem refers also the 0 age group. Maybe it will be easier if there will be an option to add the 1 year without marking it.
(Julita)

**Comment by kbekaert** [comment]
I think this should be in the SmartDots application manual with explanation on how SmartDots works (every dot is an age). So don't annotate centre and annotate edge when necessary.

**Comment by AnnelieH** [comment]
This is what is in the user manual now. 
_"Do not annotate the centre of the otolith or the outermost edge of the otolith. Only 
place a dot at the end of each winter ring as these are counted when estimating the age.
SmartDots will automatically give the age of the fish based on the number of annotations that you make."_
I can add a sentence about annotating on the edge when apporpriate. 
But I agree with Karen that it should be explained in the application manual as well.

**Comment by JaneGodiksen** [comment]
We talked about it earlier (BIOP?) to put in a colourful box in the manual. To make sure the reader actually reads it...

**Comment by AnnelieH** [comment]
I can try and do it more visible.

**Comment by JaneGodiksen** [comment]
Annelie updates the manual and closes this issue

**Comment by JaneGodiksen** [comment]
Karen: Put a page in the web application manual with a "check list" for coordinators that they need to inform the reads about - like only annotate winter rings, don't annotate the centre, only annotate the edge when .... etc etc
Annelie: And copy it into the BIOP-guidelines.
