### ISSUE TITLE
Multi-lingual interface

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#241]
Many national age readers age not fluent in English. Maybe the interface to them could be in more than one language, i.e. preferably multi-lingual.
(Uwe Krumme)

**Comment by JaneGodiksen** [comment]
This is a BIOP-related issue. Should we plan on sending out emails by early next year and ask how it is going with using the Danish screenshot version? Or should this be dealt with at WGBIOP?

**Comment by JCoadDavies** [comment]
The manual was sent to Germany and uploaded to BIOP Sharepoint. No feedback received to date so we have no idea if anyone has actually used it.

**Comment by JaneGodiksen** [comment]
I can follow up by sending an email to Uwe and ask.

**Comment by JCoadDavies** [comment]
Jane to upload the danish and german versions here and then we close the issue

**Comment by JaneGodiksen** [comment]
[SmartDots_Benutzerhandbuch kurz_DTU Aqua_übersetzt Okt 2021.docx](https://github.com/ices-eg/SmartDots/files/8529854/SmartDots_Benutzerhandbuch.kurz_DTU.Aqua_ubersetzt.Okt.2021.docx)

**Comment by JaneGodiksen** [comment]
[Brugermanual oversat SmartDots okt 2020_DTU Aqua.docx](https://github.com/ices-eg/SmartDots/files/8529857/Brugermanual.oversat.SmartDots.okt.2020_DTU.Aqua.docx)

**Comment by JaneGodiksen** [comment]
German version added to the ToR F folder under WGBIOP 2021 working documents (same place as the Danish version)
