### ISSUE TITLE
Publishing events

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#246]
Reply from WKSA chair " We published a WKSA report and included the SmartDots results and feedback as an appendix (WKSA (ices.dk)).  I think we were trying to be clear that it was was a trial – we had computers set up for people to try and there were a lot of problems with connecting or getting the event to run. Some people were just “playing” with the system and so the results were not great. I am hoping this year is easier and the event can run more smoothly"

**Comment by JCoadDavies** [comment]
@adriantait Will you be able to update on this before WGSMART on Feb 10th?

**Comment by adriantait** [comment]
@JCoadDavies I haven't heard anything since our last meeting, but have written to the chair this afternoon.  I should be able to provide an update prior to the 10th :-)

**Comment by JCoadDavies** [comment]
Thanks :-)

**Comment by JCoadDavies** [comment]
Can we change it to Type of event = testing?

**Comment by JCoadDavies** [comment]
Those with ADMIN rights to SmartDots can change "Type of Event"

**Comment by JCoadDavies** [comment]
Changed to "Test" event
