### ISSUE TITLE
What data can be shared?

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#247]
Send a request to the GDPR-team at ICES to get clarifications about what data we can share with who.
We get requests from working groups and institutes wanting to use the age readings for statistical analyses or others, and it is not clear what we can send them. 

Pri 1
Responsible: Carlos, Jane, Julie
Milestone: Q1 2022

**Comment by JaneGodiksen** [comment]
Check up on email sent to Mehdi in September. Carlos follows up.

**Comment by kbekaert** [comment]
Carlos asked to Mehdi several times, but no answer was given. Carlos follows up.

**Comment by JCoadDavies** [comment]
As the data in the reports is anonymized then there is no issue. Stock assessors can tell from the anonymized code what country the reader is from and that should be enough information for them.
There is an updated ICES Data Policy which needs to replace the 2016 version which is currently in the report and data download zip folders @cmspinto  Can you update please?
[ICES-Data-policy 2021.pdf](https://github.com/ices-eg/SmartDots/files/8650057/ICES-Data-policy.2021.pdf)

**Comment by neil-ices-dk** [comment]
@cmspinto please use this link https://doi.org/10.17895/ices.pub.8883

**Comment by cmspinto** [comment]
Done, new data policy is now in the download and the disclaimer now has the link to:  https://doi.org/10.17895/ices.pub.8883

**Comment by JCoadDavies** [comment]
Thanks - Will close the issue
