### ISSUE TITLE
Event type "Test"

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#248]
We need to make an event type called "test" to avoid confusion and make it easy to separate from normal workshops. At the moment it is often written in the name of the event that it is a test, but not all do so.

**Comment by kbekaert** [comment]
Event type should be changed to test when it is a test.

**Comment by JaneGodiksen** [comment]
It is up for discussion at the meeting Q1 22 who can set the type to test. 
At the moment a coordinator need to start the whole thing, and then hand it over to another coordinator. I think it need to stay that way. It is the coordinators responsibility what is happening in SmartDots. If everyone at an institute want to try, then the institute should get their own version - all is available for it.

**Comment by JCoadDavies** [comment]
Karen will do this.
