### ISSUE TITLE
Deactivate users

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#253]
Users who retire or for other reasons shouldn't be counted on the list of users from a country. We need to be able to deactivate them , so they still are in the system and reports. If deleted, the annotations will be deleted with them.

**Comment by JCoadDavies** [comment]
We need to know who the people are before Carlos can do this. Annelie, can we add a point to the newsletter asking country coordinators to send a message in the user feedback page telling us who from their country is not an active SmartUser....?

**Comment by cmspinto** [comment]
Would adding a retired or not available to the user help?

**Comment by JCoadDavies** [comment]
That sounds goo
@AnnelieH - can you add this to the next newsletter please :-)

**Comment by AnnelieH** [comment]
Yes I can add to the next newsletter.
