### ISSUE TITLE
Make download available of results tables

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#254]
I was coordinator of Event 280 (exchange mackerel otoliths) and we had 37 participants so it was so much information to show in the tables obtained in the SmartDots report. This information did not have enough space in the tables and was showed vertically, which was difficult to follow.

**Comment by kbekaert** [comment]
tables are created in separate csv files in the R-script. They should be made available to the event coordinator. Script will be adapted to send also the separate tables (= module folder).

**Comment by JCoadDavies** [comment]
we will add Come to this also
