### ISSUE TITLE
Vocab for edge type.

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#255]
Do we have a vocab for this and should the vocab be expanded. Suggestion from Daniel Ricard (NAFO): narrow hyaline, wide hyaline, narrow opaque, wide opaque and crystalized

**Comment by kbekaert** [comment]
Idea is to reject this issue to not complicate the interpretation of the edge.

**Comment by JaneGodiksen** [comment]
Email to Daniel Ricard on 22.04.2022
Dear Daniel,
Your question on including more edge types in SmartDots was discussed at the WGSMART Q2 meeting. 
As you know, at the moment we only have the options of choosing a hyaline edge or opaque edge. 
We believe it would be too confusing for many readers if they can choose between too many categories that are not something that will be used in their standardised assessment reading, and which are not necessary in the age analyses following the exchange in SmartDots. It is important for us that the outcome of an exchange can be used to ensure that the readers have the same understanding of the age and zonation of the otolith. And too many options will cause more uncertainty than it will be helpful.
The system has the option for the reader to write a comment, and we hope it will be enough for your readers to write the “stage” of the hyaline/opaque edge or crystallisation level in this comment field. 
I hope this will not cause too much trouble for you and your readers.
If you have any other suggestions, don’t hesitate to contact us using the feedback website (https://smartdots.ices.dk/Userfeedback). It is very important to us with any kind of feedback and suggestions for improvements. 
Best regards
Jane (on behalf of WGSMART)
