### ISSUE TITLE
who will add ichthyoplankton expertise

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#256]
Who will be the contact person for development of the eggs and larvae modules, the link between WGALES, WGSMART and WGBIOP ?

**Comment by kbekaert** [comment]
Matthias, Basti and Cindy to be contacted

**Comment by JaneGodiksen** [comment]
WGALES needs to decide if they want to work with country coordinators. Then maybe updates on the database.

**Comment by JCoadDavies** [comment]
At WGALES meeting Nov 2023 - It was agreed that WGALES will send a recommendation to the ichthyoplankton survey groups to appoint a survey coordinator to make sure that expertise of survey participants is entered into SmartDots.
