### ISSUE TITLE
Adding more filters on the user expertise page

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#257]
Filters for egg and larvae should be added. Filters for age and maturity are there, but too much information is given for one person. Filters for egg and larvae should be added.
 
![image](https://user-images.githubusercontent.com/25844933/162447830-6a0fc070-84ed-420a-84d3-a37ddd9d70ae.png)

**Comment by cmspinto** [comment]
I think that the Eggs and Larvae community are not using the expertise. 
This is something that could be discussed in WGALES.

**Comment by kbekaert** [comment]
@kbekaert, ask WGALES if they want to use the expertise
