### ISSUE TITLE
changing the Type of events

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#266]
When picking a "type of event", change "to be endorsed" into "WGBIOP". The endorsing by the WGBIOP chairs is not really working.

**Comment by kbekaert** [comment]
@cmspinto, Hi Carlos, we discussed this briefly yesterday. Can you change this in the Web application? Thank you!

**Comment by cmspinto** [comment]
Done, 

![image](https://user-images.githubusercontent.com/8705477/234196498-e6671fda-ca06-47d6-a2ca-b337fa659082.png)
