### ISSUE TITLE
Order of length and myotome annotations by type

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#268]
WKIDCLUP2 - Length and myotome annotations (lines and dots) should be ordered by their type; Suggested order: myotome; myotomes pylorus-pelvic; Total length; Stdt. Length; head length. It was considered easier to start with myotome count and then the length measurements. Otherwise myotomes would be difficult to recognize under the lines of the measurements.

**Comment by wimallegaert** [comment]
the parameters are sorted alphabetically. The name of the parameters can be set in the Web API. If you want a specific order you can start the parameter name with a number
