### ISSUE TITLE
ICES area and Statistical Rectangles references and lookups

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#27]
@Jane who asked about lookups for ICES areas:

http://gis.ices.dk/sf/index.html?widget=StatRec
or from the [Reference layers] menu select ICES Areas or Stat Recs

**Comment by cmspinto** [comment]
I'm under the impression this task is really simple. 
I think it is only to put the link but I'm not use if the link should go to the template or to the upload page?
