### ISSUE TITLE
SmartDots Dataflow

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#279]
Dataflow needs a final check from WGSMART before publishing

**Comment by JCoadDavies** [comment]
[DataFlowSmartDots-1.pdf](https://github.com/ices-eg/SmartDots/files/9839108/DataFlowSmartDots-1.pdf)

**Comment by neil-ices-dk** [comment]
> [DataFlowSmartDots-1.pdf](https://github.com/ices-eg/SmartDots/files/9839108/DataFlowSmartDots-1.pdf)

thanks Julie - if you have comments just put them here on a post it on the pdf versio and then we'll have a look. I'm in the office tomorrow (Tuesday), so i can pop by if there is a need for a chat.

**Comment by JCoadDavies** [comment]
The last meeting on this was with Joana 13/11
She will finalise.
@pcrjoana is this ready now?

**Comment by pcrjoana** [comment]
@neil-ices-dk is in the process of reviewing it now, and once he's happy with the schematic, we'll prepare it for publication.

**Comment by JCoadDavies** [comment]
[DataFlowSmartDots_edits.pdf](https://github.com/ices-eg/SmartDots/files/13648625/DataFlowSmartDots_edits.pdf)

The text in Definition of Data Required has been updated and highlighted in yellow. The file is also on WGSMART SP under 2023 Working Docs
