### ISSUE TITLE
Instructions in manual on pinning the annotation line

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#281]
Fixing the reading line: there is limited information in either of the manuals regarding fixing the reading line

Suggestion (cited from internal SOP):
x Open smartdots app, enter your token and pick your event.
x As the delegate/event manager you must fix the reading line to each image. That line will be the same for each reader to ensure consistency of ageing process. The reading line should start in the centre of nucleus. The reading line can be adjusted to the shape of otolith; it does not have to be straight. Good practice is to extend the line beyond the edge of otolith so it is easier to annotate in that area. Once you draw the line it must be pinned to the image by clicking on the ‘PIN’ button. As you open each image the first and only thing you can do is to draw the line. Please choose the clearest axis to facilitate optimum ageing interpretation. The colour and width of the line can be changed- by expanding ‘pencil’ button on top of the imag

**Comment by kbekaert** [comment]
added in software manual
