### ISSUE TITLE
Colour of readers for discussion

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#291]
When viewing multiple readers annotations on an image for discussion purposes it is very difficult to follow which annotations belong to which readers when the colours of the dots assigned to a reader change when a second (and more) readers annotations are selected for viewing with the other annotations that were previously selected. Is it possible to assign dot colours to a reader and use them consistently from image to image?
Sent by Julie Davies

**Comment by wimallegaert** [comment]
When a coordinator checks the annotations of an event, the colour linked to the user should be the same for all his/her annotations in the selected event.

A key-value list will be kept in memory, in this list a colour is linked to a user. 

- The base is a list with 30 colours
- Everytime a new user is detected, the user will be linked to the next colour. 
- When the coordinator navigates from the agereading, maturity, …module to the events module the key-value list will be reset.

 To be clear: the colour-user relation is stored in memory, not in the database. If this is needed an extension of the API is also needed.
