### ISSUE TITLE
Area information

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#294]
From WKMACHIS (Workshop on Mackerel, Horse Mackerel and Hake Eggs Identification and Staging) on sample information: instead of given FAO/ICES area location information only, which not everyone knows by heart, a more explicit information on the catch location would be very helpful.
Sent by Matthias Kloppmann (matthias.kloppmann@thuenen.de)

**Comment by JaneGodiksen** [comment]
Map?
Add link to ICES vocab.

**Comment by wimallegaert** [comment]
An extra link will be added in the Help menu to the vocab ices areas: [vocab.ices.dk/?ref=358](https://vocab.ices.dk/?ref=358)

**Comment by wimallegaert** [comment]
add a link to https://www.ices.dk/data/Documents/Maps/ICES-Ecoregions-hybrid-statistical-areas.png

**Comment by JCoadDavies** [comment]
@cmspinto Can you please put it here
![image](https://github.com/ices-eg/SmartDots/assets/26571227/6a214243-4ec7-439a-8cc8-744214912f04)

**Comment by cmspinto** [comment]
In the grid?

**Comment by JCoadDavies** [comment]
A link in the help menu
