### ISSUE TITLE
Optimize preloading of images in SmartDots software

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#299]
In the current version the image linked to the next sample is automatically preloaded (and stored on the local hard drive). 

It could be useful to integrate an option so the user can decide to preload all images from the event at once. The user should be informed about the size of the download. There should also be an option to delete the downloaded images (or access the directory). 
This functionality could be integrated as 2 new options in the settings menu:

- automatically preload images + checkbox
- link to delete all cached images (+show info about the total file size)

An extra setting is needed to identify of the download option is available for the active Web API.
An extra API method will be needed to download all event images at once.

**Comment by wimallegaert** [comment]
linked to [https://github.com/ices-eg/SmartDots/issues/298](url) and [https://github.com/ices-eg/SmartDots/issues/295](url)

**Comment by kevinatilvo** [comment]
Preloading sounds nice on paper but a slow wifi connection will remain slow. Here are some thoughts about this feature to take into consideration with an example use case:

Assuming preloading happens per event...
Say 1 large image takes 8 seconds to load on a slow wifi connection.
The (maturity) event has 100 samples with each 3 large images. So the total is 300 large images.
It will take 1 user 40 minutes to download all images.
It will take 20 users on the same wifi connection over 13 hours to preload all images.

In the case above you would not be able to start reading/annotating the same day. You would wish the preloading was not a feature.

Another thing to think about is how long will the images be stored on the user's hard drive? The user will probably have to clean it up manually.

**Comment by JCoadDavies** [comment]
Is preloading and downloading images the same thing? 
We have a note on downloading but perhaps this can be deleted

**Comment by wimallegaert** [comment]
> Is preloading and downloading images the same thing? We have a note on downloading but perhaps this can be deleted

Indeed, this is the same topic: "Make pictures downloadable before annotating an event (faster switch between images) "

**Comment by wimallegaert** [comment]
estimate of software development time: 10 days 

functionality will be available for all event types (age reading, maturity, eggs, larvae)
a new Web API method need to be developed bij ICES.
