### ISSUE TITLE
Approve and Unapprove

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#303]
When a user approve and unapprove an annotation (delegate or a organizer) then it does it for all annotations.

![image](https://user-images.githubusercontent.com/8705477/201876422-6206a7ce-4a6c-4d8b-a8ee-8fd35d49f4e8.png)

**Comment by cmspinto** [comment]
Approved is now working fine, but the sex, maturity and QC are not working as expected after updating an annotation.

This could be difficult to debug, only a delegate can observe this bug, when a coordinator makes an annotations, the listed annotations in the software get the same values as the new annotations.  Have checked the API and is seemed to me that the API is working as expected, so need to check the software to see if we can find the bug.

![image](https://user-images.githubusercontent.com/8705477/202136435-4ab4ee97-ae2a-47b6-adba-ec8f149f926f.png)

Before making the annotation:

After:
![image](https://user-images.githubusercontent.com/8705477/202136226-50bb45db-682a-4ba2-b682-3245e4ba43f0.png)

**Comment by kevinatilvo** [comment]
@cmspinto Bug discovered in the software that causes this problem. Thanks for documenting it.

**Comment by wimallegaert** [comment]
This is solved
