### ISSUE TITLE
Youtube channels

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#305]
Put link on ices youtube channel from SmartDots and vice versa.

**Comment by wimallegaert** [comment]
There is a link in the Help menu of the software: ICES trainings videos.

In the channel section a link to ICES channel was added
In the about section of the YouTube channel is a link to ICES channel

**Comment by wimallegaert** [comment]
ICES should add a link to the youtube channel from [https://www.youtube.com/@ICESmarine/channels](url) to [https://www.youtube.com/@icessmartdots2352](url)
