### ISSUE TITLE
Create a SmartDots landing page in SharePoint.

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#31]
Page should point to the:
* [x] download of the software
* [x] smartdots management

**Comment by neil-ices-dk** [comment]
i need more than this to create landing page:
- intro text
- links to relevant group
- Data policy
- and the links to the 2 items you mention above

**Comment by wimallegaert** [comment]
some info for the landingpage in attachment

[SmartDots info ICES webpage.docx](https://github.com/ices-eg/SmartDots/files/1477649/SmartDots.info.ICES.webpage.docx)
[Smartdots images.zip](https://github.com/ices-eg/SmartDots/files/1477651/Smartdots.images.zip)

**Comment by neil-ices-dk** [comment]
thanks Wim, will take a crack at the page

**Comment by neil-ices-dk** [comment]
page created http://ices.dk/marine-data/tools/Pages/smartdots.aspx 
intro done
logos added

@cmspinto shouldn't this be https:?? http://smartdots.ices.dk/manage/index.aspx

**Comment by neil-ices-dk** [comment]
- ok now linking to https://smartdots.ices.dk/manage/index.aspx
- the annex 8 from WGBIOP needs to be formatted into a stand alone user guide, have asked Rui to reach out the appropriate supporting secretary to get this done

**Comment by wimallegaert** [comment]
Which url can we use for the smartdots download location? Is http://smartdots.ices.dk/download possible?
Once we know the url we'll create an click-once exe file of the actual stable version.

**Comment by neil-ices-dk** [comment]
that would work :)

**Comment by neil-ices-dk** [comment]
@cmspinto i've made a sharepoint folder which you will need to map back to http://smartdots.ices.dk/download

http://ices.dk/marine-data/Documents/Forms/AllItems.aspx?RootFolder=%2Fmarine%2Ddata%2FDocuments%2FSmartdotsDownload&FolderCTID=0x012000ACF6FBA45737584389AD23DD43BB914C&View=%7B2B052244%2DC349%2D4A52%2DA17C%2D88C6E0970742%7D

**Comment by cmspinto** [comment]
Ok, and what is the name of the file?
Can I redirect the current home page to the one in the sharepoint?

**Comment by neil-ices-dk** [comment]
re: homepage - yes, redirect
re: download/ - there is no file yet

**Comment by cmspinto** [comment]
Done 👍 

http://smartdots.ices.dk/

**Comment by neil-ices-dk** [comment]
regarding the download, who is waiting for whom? Carlos is waiting for Wim, Wim is waiting for Neil? Do i need to do something further?

**Comment by wimallegaert** [comment]
we'll create a click-once smartdots file and send it to you
