### ISSUE TITLE
Redo video tutorials

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#311]

**Comment by JCoadDavies** [comment]
Notes on what needs updating in the YouTube tutorials were created during subgroup work at the 2 day meeting, attached
[WGSMART YouTube tutorials for event organisers and users_old vs new.docx](https://github.com/ices-eg/SmartDots/files/10102492/WGSMART.YouTube.tutorials.for.event.organisers.and.users_old.vs.new.docx)
