### ISSUE TITLE
feedback from maturity testing

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#312]

**Comment by kbekaert** [comment]
[Feedback Test Maturity module.docx](https://github.com/ices-eg/SmartDots/files/10092638/Feedback.Test.Maturity.module.docx)

**Comment by wimallegaert** [comment]
Feedback from ILVO ICT: [Feedback Test Maturity module.docx](https://github.com/ices-eg/SmartDots/files/10093368/Feedback.Test.Maturity.module.docx)

**Comment by cmspinto** [comment]
That was a very good idea Wim, 
I guess we will check this in the next WGSMART or should we touch base before?

Some of the issue are really simple.

**Comment by cmspinto** [comment]
Good news, we are almost there.

There are one or two issues to solve and a few questions from our side. 
Should we try to put these on issues bellow? (this is because we need feedback before solving one or two issues)

Here the ICES feedback:
[Feedback.Test.Maturity.module.docx](https://github.com/ices-eg/SmartDots/files/10176315/Feedback.Test.Maturity.module.docx)

**Comment by cmspinto** [comment]
I was just with @kevinatilvo and he help me to solve the last issues :)

I guess we should be ready for another round of testings soon.

[Feedback.Test.Maturity.module.docx](https://github.com/ices-eg/SmartDots/files/10177392/Feedback.Test.Maturity.module.docx)

**Comment by wimallegaert** [comment]
> @CindyvanDamme and @wimallegaert need help on this issue:
> 
> > Shouldn´t be annotations locked until unapproved button is pressed? It happened to me that trying to change it, the message of “..event as finished?” pops up and then pressing “No” the value I tried to change before, is changed.
> 
> > Feedback ILVO ICT: to be checked in the web API logic. If a sample is approved the sample should be marked as read-only. If the sample is set read-only all the annotation properties are locked.
> 
> My question: Does this means after approving an annotation the user can’t change it anymore for that fish? So that fish becomes read-only for that user?

According to me that is correct. If a user approves his/her annotation then the annotation becomes read-only. If he/she wants to change something on the approved annotation then he/she first has to 'disapprove' the annotation.

**Comment by kbekaert** [comment]
Hi all, Thanks a lot to the testers and of course to the developers for the work done. I think it looks great! ! I gathered all feedback from the testing (Marcin, Maria and myself) in one document. It might be necessary to discuss and agree on a few issues. 
[Feedback.Test.Maturity.module_Maria_Karen_Marcin.docx](https://github.com/ices-eg/SmartDots/files/10216644/Feedback.Test.Maturity.module_Maria_Karen_Marcin.docx)

**Comment by MKAlbisua** [comment]
@cmspinto can I ask you to reopen the maturity module testing event, so we can make screenshots and include them in the software manual? Thank you!

**Comment by cmspinto** [comment]
@MKAlbisua , is it event 502? It's open. I added you to that event.
If you are testing with another event let me know the ID and I will open the event.

**Comment by MKAlbisua** [comment]
@cmspinto , yes it is the event 502. But I have readonly rights, because I set the event as finished..

**Comment by cmspinto** [comment]
Done :). Event is open again for everyone.

**Comment by MKAlbisua** [comment]
thank you!
