### ISSUE TITLE
Data license

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#320]
SmartDots can now copy an event, we receive some request to copy the events. 
To be able to automate this task we need to have a clear data license in place, so that a user when creating an event knows under what license will be their samples.

**Comment by JCoadDavies** [comment]
[ICES-Data-policy.pdf](https://github.com/ices-eg/SmartDots/files/11625556/ICES-Data-policy.pdf)

So we have this. If it does not cover it then we need some guidance on what to do.
