### ISSUE TITLE
Show message when using guest token button

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#321]
People seem confused with the guest token.

**Comment by JCoadDavies** [comment]
We will have a pop up text box appear when you click on the GET GUEST TOKEN which will warn that a reader is entering an event. Julie and KAren to give Carlos text

**Comment by CindyvanDamme** [comment]
> Text suggestion "You are entering SmartDots as a guest where you can only view published events. If you want to annotate a specific event please use your personal ICES token"

Should it not be public events instead of published? Because when I use the guest token I see 'Event is public' but user progress is 'Ongoing' and an end date end of 2023.

And should it be 'use your personal ICES login and token'?

**Comment by wimallegaert** [comment]
Message sent via Web API: You are entering SmartDots as a guest where you have read-only access to the public events. If you want to annotate a specific event please use your personal ICES login and token.

**Comment by JCoadDavies** [comment]
Tested this and no warning message appeared

**Comment by kbekaert** [comment]
@wimallegaert to investigate
