### ISSUE TITLE
From automated mails for larvae and eggs and maturity events the link to the Web event needs to be removed

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-eg/SmartDots#323]
When a new larvae or egg event is created the automated mail that is sent to the participants still contains the link for annotation on the SmartDots webpage (see the mail text below here). Also there is still the possibility to annotate on the web.

The link in the mail should be removed and the possibility to annotate on the Web be disabled.

Dear [cindy.vandamme@wur.nl](mailto:cindy.vandamme@wur.nl),

You have been listed as a participant (Role:Organizer) for SmartDots event ID 715 - WMR internal Clupeid ID workshop 2023 which is scheduled to begin on 30/09/2023 00:00:00. 

You can start annotating the event [here](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsmartdots.ices.dk%2Fmanage%2FViewEvent%3FtblEventID%3D715&data=05%7C01%7Ccindy.vandamme%40wur.nl%7Cbde403194af4402c4c2108dbc0c22aed%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C638315712395848108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eo2Sh9UHf21%2FkhdsPGx2oSVAqd6d5QELcczjJN%2FtWTA%3D&reserved=0)

Best regards,

The SmartDots team

**Comment by cmspinto** [comment]
Done.
