### ISSUE TITLE
Growth graph - viewing all annotations from a reader in one graph as a visual check for inconsistencies

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#333]
It would be interesting to have in the "Growth" graph, an overlay of all the growth curves of the sample batch to be analyzed. This will help to detect false rings (thanks to the distances between rings). It will also be possible to detect changes in magnification with a different calibration that should challenge the age reader. 
Comment by romain.elleboode@ifremer.fr

Julie has replied Romain. But I can't find the issue. Delete if I have just overlooked it.

**Comment by wimallegaert** [comment]
Extra info: this will be a new module / chart. By default the annotation data is loaded image by image. For this we'll need a new Web API method which load all annotations for all the images of the event.
