### ISSUE TITLE
Remove funcionality of adding a watermark to the pictures. 

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#339]

**Comment by wimallegaert** [comment]
- Create an event: checkbox  "I agree with the ICES data policy" (+ link to policy page) 
- Publish an event: 
		○ Remove the functionalitity to add a watermark to the pictures
		○ Notification that images and annotations will become public
- Upload Sample file: Add an extra column on sheet File_information for institute that is owner of the images.

**Comment by kbekaert** [comment]
@pcrjoana and @cmspinto, can you arrange who will add the extra column in the SmartDots upload file? Thanks!

**Comment by pcrjoana** [comment]
Format and template updated. @neil-ices-dk to upload the template and @cmspinto to implement the necessary changes to the database and website.

**Comment by cmspinto** [comment]
This is now done, can we close the issue?

**Comment by kbekaert** [comment]
Hi Carlos, Thanks! 
Did you also remove the functionalitity to add a watermark to the pictures and  add a notification that images and annotations will become public when publishing an event? I couldn't test this.

**Comment by kbekaert** [comment]
@cmspinto can you please unpublish event sole 7a ID 1842 so that I can test?

**Comment by kbekaert** [comment]
Tested and OK: only one option left.
