### ISSUE TITLE
Update SmartDots Sharepoint page  according to the CC BY 4.0 license

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#342]
Add link on https://www.ices.dk/data/tools/Pages/smartdots.aspx "Guides and standards" to ICES Data Policy: https://www.ices.dk/data/guidelines-and-policy/pages/ices-data-policy.aspx

**Comment by neil-ices-dk** [comment]
@wimallegaert i would propose to do it to align with the other data portals:
![image](https://github.com/ices-eg/SmartDots/assets/23527005/95d012ad-8848-4204-8dab-a5271b29570f)

at the same time, i also added a standard suggested citation - can you check with WGSMART if that is fine or whether it needs adjusting. Neil

![image](https://github.com/ices-eg/SmartDots/assets/23527005/f2417942-9818-4aba-8047-3eece2aa2f30)

**Comment by JCoadDavies** [comment]
@neil-ices-dk 
This is fine with WGSMART. We will ask that all published reports cite SmartDots
Thanks
