### ISSUE TITLE
Typo on the eggs module in the software

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/SmartDots#345]
There is a typo on the eggs module in the software. "Method" is spelled as "matod", and "analysis" is spelled "analisys".

**Comment by pcrjoana** [comment]
![image](https://github.com/ices-eg/SmartDots/assets/49305340/acee260b-71e1-45e7-b2ac-79f9727d5bae)

**Comment by pcrjoana** [comment]
![image](https://github.com/ices-eg/SmartDots/assets/49305340/083b5ad3-30fb-44d4-bf2f-9f6d33d22f29)

**Comment by JCoadDavies** [comment]
These are questions added by the event coordinator, so can only be modified by them in the web app
