### ISSUE TITLE
For Q1 2024 newsletter

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#348]
When co-ordinators and/or chairs of exchanges and workshops have feedback on SmartDots it needs to be posted in the ICES SmartDots feedback page. When a report is published, SmartDots should be cited in the reference list as is mentioned on the SmartDots landing page. 
![image](https://github.com/ices-eg/SmartDots/assets/25844933/41052dff-0740-40ef-a089-09d8e7137dbc)

**Comment by kbekaert** [comment]
download the latest version of the upload file

**Comment by kbekaert** [comment]
@AnnelieH, can you add these 2 points in the newsletter as well? Thank you!
