### ISSUE TITLE
Correcting the maturity report code.

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#353]
- multi modal stage tables are incorrect
- duplicated lines in results overview tables 
- missing PA and CU in the results overview tables 
- for samples with histology: the stage of the coordinator is not taken as correct stage, the modal stage approach is still used
- include raw data files in .zip

**Comment by gonpatricia** [comment]
The need modification had been concluded.

**Comment by gonpatricia** [comment]
Corrections finalized ;)
