### ISSUE TITLE
Setting the scale in the webapp: decimal point

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#357]
Feedback from the egg and larvae training course on setting the scale in the webapp: when setting the scale in the web app it is now possible for a user to enter a number with a decimal point BUT the system will not accept a decimal point.
A warning needs to be added here

**Comment by cmspinto** [comment]
This is done: 

![image](https://github.com/user-attachments/assets/cd50d128-1ee9-4c3d-b864-d46e61c9792a)
