### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#360]
Make it possible to create keyboard shortcuts to streamline a series of actions for experienced users, or even for routine laboratory use in production mode. In Ifremer Boulogne, we have small soft for that. Feedback by Romain Elleboode

**Comment by rellebo** [comment]
The first phase involves identifying the line on the calcified part and the subsequent annotation, a step that cannot be optimised without the integration of artificial intelligence.
However, by introducing the parameter next and previous navigation buttons, we can automate subsequent actions based on the AQ list.
For example, by pressing the A button after the age estimate, it would be possible to automatically select AQ1 by following the approve and next photo (with navigation buttons). Similarly, by using the letter Z after the age estimate, AQ2 could be selected approve and next, and so on with the letter E for AQ3, and so on. I will send an email with video loom and .exe.

**Comment by rellebo** [comment]
https://filesender.renater.fr/?s=download&token=7d2393cf-424c-41aa-989f-f14e50f62557
