### ISSUE TITLE
Quick overview of results in software

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#361]
"My feedback is about the results for participants. I think it would be convenient they could also get an overview of the results to see quickly where there results are different. This saves time and you do not have to go through all the samples"

This is true for the person analysing the results and writing the report also. The results need to be pulled out and those with poor agreement identified from the data/report and then found in the software so the image can be checked to see where the disagreement is.

**Comment by kbekaert** [comment]
Add a overview table in the report containing the samples with a low agreement (e.g. <60%).

**Comment by kbekaert** [comment]
Move to production @cmspinto - Thank you Carlos!

**Comment by AnnelieH** [comment]
Added to newsletter.
