### ISSUE TITLE
Corrections to be made in age reading report

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#370]
From AR report sole 7a event 1842: 
- in annex graph: "relative bias for all readers": order of Y-axis values is not correct in the negative values, distance between values always the same even though the value is not, there is no modal age "0" in the exchange, add red dotted line at relative bias 0 (as is for the same graph in the advanced readers). 

![image](https://github.com/ices-eg/SmartDots/assets/25844933/da6b6fa9-4d3a-4336-a152-86f4b45d0759)

- in same graph for advanced readers: change title from "all readers" to "advanced readers" 

![image](https://github.com/ices-eg/SmartDots/assets/25844933/593f2e07-2488-458b-978f-4c09d1bf09f7)

**Comment by ComeDenechaud** [comment]
Reporting script has been edited to produce the proper plot (real numerical Y scale). Changes visible for SmartDots events pending merging of development and master branches
