### ISSUE TITLE
Develop a SmartDots disclaimer

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#41]
We need a disclaimer for smartdots to come when people make the download of data.

**Comment by cmspinto** [comment]
A template for the disclaimer
[Smartdots_Disclamer_draft.docx](https://github.com/ices-eg/SmartDots/files/3211747/Smartdots_Disclamer_draft.docx)
:.

**Comment by kbekaert** [comment]
Need to check with Loes and Rui what's the status of this.

**Comment by JCoadDavies** [comment]
[Smartdots_Disclamer_draft_loes.docx](https://github.com/ices-eg/SmartDots/files/3720480/Smartdots_Disclamer_draft_loes.docx)
[Smartdots_Disclamer_draft.docx](https://github.com/ices-eg/SmartDots/files/3720481/Smartdots_Disclamer_draft.docx)
[Disclaimer_Exchange Data_2019-09-23 09_57_56.txt](https://github.com/ices-eg/SmartDots/files/3720482/Disclaimer_Exchange.Data_2019-09-23.09_57_56.txt)


Files above provided by Loes at WGBIOP 2019 and requested review by ICES & software-people...

**Comment by JCoadDavies** [comment]
missing feedback from 
@neil-ices-dk 
@Rui-Catarino

**Comment by neil-ices-dk** [comment]
will take a look this week :)

**Comment by neil-ices-dk** [comment]
ok, i am currently reviewing the generic ICES data disclaimer that the templates you are using are based on. So i can foresee some changes once this is completed. I'm just awaiting feedback and then we can take a look together - it's not massively different but more updated and consolidated. One issue is that we collect IP addresses, which are considered under GDPR.

**Comment by neil-ices-dk** [comment]
[ICES Generic disclaimer review_v3.docx](https://github.com/ices-eg/SmartDots/files/3977261/ICES.Generic.disclaimer.review_v3.docx)
@JCoadDavies @kbekaert ladies - back to you - this is the 'new' version of the ICES generic disclaimer that we will use on all data portals - there is a section that is specific to the portal in question, and i guess where it will need your SmartDots eyes on.

**Comment by JCoadDavies** [comment]
[ICES.Generic.disclaimer.review_v3_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4224284/ICES.Generic.disclaimer.review_v3_SmartDots.docx)

Hi! I have taken part of what Loes had initially written for the first disclaimer and adapted it. @neil-ices-dk Do we need to add more?

**Comment by neil-ices-dk** [comment]
Thanks Julie, will take a look and get back to you 👍

**Comment by neil-ices-dk** [comment]
Couple of comments back:
- assume you will delete the other text (DOME etc) in the 'Data Specific Information'
- For the new website/GDPR disclaimer, this is still in preparation and most likely ready by the end of March; In the meantime, we have agreed that we do not need to record the users IP address, so you can delete '_by IP IPADDRESSXXX._' from the text
- for Metadata, there is an entry in our catalogue that you should include https://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/327bd628-bf74-43d4-8425-11733e2df265

**Comment by neil-ices-dk** [comment]
i forgot this one, you had a question about DATSU, there is something there for SMARTDOTs but check with Carlos [https://datsu.ices.dk/web/rptChk.aspx?Dataset=129](https://datsu.ices.dk/web/rptChk.aspx?Dataset=129)

**Comment by JCoadDavies** [comment]
Thanks Neil. Updated now with 2 questions: 
1. LAYERNAMEXXX, requested from www.xxxxxxxxxxxxxxxxxxx on DATETIMEXXX - Does this remain like this and then xx's filled in automatically at time of download?

2. @cmspinto can you please help with the comment on the data format, see comment in the file.

[ICES.Generic.disclaimer.review_v3_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4235203/ICES.Generic.disclaimer.review_v3_SmartDots.docx)

**Comment by neil-ices-dk** [comment]
> LAYERNAMEXXX, requested from www.xxxxxxxxxxxxxxxxxxx on DATETIMEXXX - Does this remain like this and then xx's filled in automatically at time of download?

Yes - this is automated :)

**Comment by JCoadDavies** [comment]
[ICES.Generic.disclaimer.review_v3_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4485384/ICES.Generic.disclaimer.review_v3_SmartDots.docx)

@cmspinto Carlos can you please check the comment for you.
This is the final version

**Comment by cmspinto** [comment]
[ICES.Generic.disclaimer.review_v4_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4616287/ICES.Generic.disclaimer.review_v4_SmartDots.docx)

Have review the disclamer, this is aplicable for the public events and the download is suppose to be the source of the R script. 

Currently it only has three files: 
![image](https://user-images.githubusercontent.com/8705477/81705406-4cdc2d00-946f-11ea-90dd-3c9553a3ce46.png)

But in future the disclamer will come in the download.

**Comment by JCoadDavies** [comment]
[ICES.Generic.disclaimer.review_v4_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4620420/ICES.Generic.disclaimer.review_v4_SmartDots.docx)

I checked the links in the document and they are not working anymore, I assume this is after the ICES webpage has been updated. Can you please help. There is also a comment on the Contact Info and Data Specific Information.

**Comment by cmspinto** [comment]
Thanks for the heads up. 

Corrected the links in the document

[ICES.Generic.disclaimer.review_v5_SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4620453/ICES.Generic.disclaimer.review_v5_SmartDots.docx)

**Comment by JCoadDavies** [comment]
Thanks Carlos

@neil-ices-dk Hi Neil, this should be final and ready.

[ICES.Generic.disclaimer.SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4620526/ICES.Generic.disclaimer.SmartDots.docx)

**Comment by neil-ices-dk** [comment]
@JCoadDavies and @cmspinto looks good - one small addition. In the 'Data specific section' you could add (part in bold):

All source code is publicly accessible **and under the terms of a General Public License (https://github.com/ices-eg/SmartDots/blob/master/LICENSE)**

**Comment by JCoadDavies** [comment]
Done
[ICES.Generic.disclaimer.SmartDots.docx](https://github.com/ices-eg/SmartDots/files/4633755/ICES.Generic.disclaimer.SmartDots.docx)
 @neil-ices-dk @cmspinto i guess this is now up to you to make it available with the report and data download

**Comment by cmspinto** [comment]
Disclamer is not part of the download. 

![image](https://user-images.githubusercontent.com/8705477/84584555-14c96080-ae06-11ea-91bd-0b587870d140.png)

@JCoadDavies, @JaneGodiksen need to check the part of acknowledge data source.

**Comment by JCoadDavies** [comment]
Sorry, I am a little confused...the Disclaimer is part of the download, I just downloaded and it is there. So i don't see what needs to be checked. 
Can you be more specific @cmspinto

**Comment by neil-ices-dk** [comment]
> 
> 
> Disclamer is not part of the download.
> 
> ![image](https://user-images.githubusercontent.com/8705477/84584555-14c96080-ae06-11ea-91bd-0b587870d140.png)
> 
> @JCoadDavies, @JaneGodiksen need to check the part of acknowledge data source.

while you are at it, could you change the spelling of the file to 'disclaimer.txt'  thanks :)
