### ISSUE TITLE
Modal age in the view event page

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#49]
Julie: Modal age is only visible to the event manager/co-ordinator. It should be that you can filter for the modal age “Select an age” i.e. 1,2,3,4,5. I think the calculation of modal age (even if it is temporary until published) needs to be based on the same calculation as the modal age from the analysis as this will depend on the ordering of the readers. If we can only re-order the readers once the event is closed then we should exclude this option here.

**Comment by JaneGodiksen** [comment]
We don't want to add modal age after an exchange, as this is not necessarily the correct age. Instead, we could use this feature for the agreed age reference collections.

**Comment by JCoadDavies** [comment]
We still do not have the possibility to search for samples by age and this would be very useful.

**Comment by JCoadDavies** [comment]
Adding a milestone for the Nov 2021 meeting so that we can take this up there and decide whether to close or not

**Comment by JCoadDavies** [comment]
Q1 meeting 2022 - NEED TO DECIDE UPON
