### ISSUE TITLE
Analysis of SmartDots web API 

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#5]
Get methods (read):
- Get activities (in: Username + pwd) (out: workshop + role)
- Get sample data (in: workshop ID) (out:file,  annotation, sample data)
Set methods (insert, update, delete):
- Set line
- Set dots

**Comment by wimallegaert** [comment]
[HttpPost]
        **[Route("authenticate")]**
        //Returns the User if authentication is succeeded
        public string Authenticate([FromBody] UserAuthentication userauthentication)
                               
        [HttpGet]
        **[Route("getsettings")]**
        //Returns a SmartdotsSettings object with the institute depending settings
        public string GetSettings(string token)

        [HttpGet]
        **[Route("getqualities")]**
        //Returns a List<Quality> of AQ quality codes
        public string GetQualities(string token)

        [HttpGet]
        **[Route("getanalysis")]**
        //Returns either a List<Analysis> or a single analysis if an ID or number is provided
        public string GetAnalysis(string token, Guid? id = null, int? number = null)

        [HttpPost]
        **[Route("getfiles")]**
        //Returns a list of files from the imagenames provided in the class
        public string GetFiles(string token, [FromBody]CheckFilesClass fileinfo)

        [HttpGet]
        **[Route("getfile")]**
        //Returns a single file with all linked annotations and with sampleproperties if desired
        public string GetFile(string token, Guid id, bool withAnnotations, bool withSampleProperties)

        [HttpPost]
        **[Route("deleteannotations")]**
        //Deletes an annotation, returns true if succeeded
        public string DeleteAnnotations(string token, [FromBody] List<Guid> ids)

        [HttpPost]
        **[Route("updateannotations")]**
        //Saves annotations, returns true if succeeded
        public string UpdateAnnotations(string token, [FromBody] List<Outcome> annotations)

        [HttpPost]
        **[Route("updatefile")]**
        //Updates a file, returns true if succeeded
        public string UpdateFile(string token, [FromBody] File file)
        
        [HttpPost]
        **[Route("addannotation")]**
        //Adds a new annotation, returns true if succeeded
        public string AddAnnotation(string token, [FromBody] Outcome annotation)
