### ISSUE TITLE
Functionality for the reader to signalize that he has finish the exercise

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#56]
Julie: 2.	I think we need to have a button in the SmartDots tool that a reader clicks when they are finished with annotating their exercise

**Comment by JCoadDavies** [comment]
"This can  be handled with an extra button on the activity page. 
 - An extra button ""age-reading completed"" will be added in the toolbar on the activity page
 - If the user select an event/activity the button ""age-reading completed"" will be active
 - An new web method will be developed to manage this user-event status
 - If the user click the button a Wep API is triggered, the data will be send to the database 
 - After clicking the button, the event-list is reloaded. The user-event status can be shown in an extra column.
 - Integrate ""CanMarkEventAsCompleted"" as an extra  property in theSmartDotsSettings Web API method (default value =  false)"

**Comment by kevinatilvo** [comment]
Does there need to be a button to undo the completing?

**Comment by JCoadDavies** [comment]
Yes, I think that would make sense. There will be instances where the readers may need to go in and "fix" somethings i.e. approving annotations or annotating an image which they have forgotten.

**Comment by kevinatilvo** [comment]
A new button was added on the Event overview screen. This “Finished/Reopen”-button is only enabled when the data contains a column “User Progress”.
 
![image](https://user-images.githubusercontent.com/25780423/57923592-00353480-78a3-11e9-8c85-e0abbc5f98a7.png)

Clicking on the button sends a signal to the Web API to Finish or Reopen the selected event. The owner of the Web API can decide if he/she allows the user to enter a Finished event. I have chosen to display an error message.
 
![image](https://user-images.githubusercontent.com/25780423/57923603-04615200-78a3-11e9-8a40-d6be5ecca9f8.png)
