### ISSUE TITLE
Resize of the columns (software)

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#57]
Julie: Column spacing is adjustable but when I resize the columns so that I can see the full names of the events (this is important especially for the readers) and I logout and return the spacing I have choosen is not saved.

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/37390377-220f2ddc-2768-11e8-8e5d-a7a372a71ba3.png)

**Comment by kevinatilvo** [comment]
You are correct. This one works a bit different than the other tables, because it can display any data that is given to it, compared to the others which have fixed Columns.
