### ISSUE TITLE
Color of the dots (for each user)

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#60]
1.	Can we restrict readers from choosing the same size and colour of the dots once another reader has chosen a combination of dot size and colour. I can see that Rasmussenh and gillespiemules (Event 74) are using the same combination of size and colour (I think the default). This is confusing!

**Comment by cmspinto** [comment]
develop a functionality in the view event for the manager to change the color of the dots for a specific user

**Comment by wimallegaert** [comment]
This wish will also have an impact on the Web API and SmartDots. Now the user can change manually the colour in SmartDots. If we want to restrict the choice, colour data should be passed to SmartDotsvia the Web API . With an extra setting we could prevent that the user can change the colour.

The size of a dot or line is changeable in function of the resolution of the picture.
