### ISSUE TITLE
Develop ToR's for a formal Governance Group: GGSmarts

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#69]
**Outline from webex meeting 7th June 2018**

**a.	Chairs**
 
•	It was agreed that the governance group should have co-chairs. 
•	Also agreed that the sitting chair of WGBIOP should be one of the co-chairs
•	The second co-chair should be someone with new perspective. Bringing ideas to the table.
•	Rotation of chairs every 3 years
Jane's name was put forward as potential co-chair
 
**b.  Frequency of meetings**
 
•	Proposal was made that in an initial stage the group should met via WebEx more frequently
•	Also proposed that the Group should meet physically at least once a year (timing to be discussed at a later stage)    
 
**c.  Membership of the Group**
•	Chair of WGBIOP
•	One member from each country from the core development group (Belgium, Denmark, Norway)
•	ICES
•	Invitation to be extend to other countries at WBIOP but with a cap for a maximum of 10 members for the all group.
 
**d.  Aims of the Group**
•	  ICES to provide a draft of a governance group framework, using the DATRAS GG has an example.
•	The draft to be discussed in a future meeting.

**Comment by neil-ices-dk** [comment]
First draft of ToR's based on above discussion
[SmartGG.docx](https://github.com/ices-eg/SmartDots/files/2101808/SmartGG.docx)

**Comment by JCoadDavies** [comment]
[SmartGG.docx](https://github.com/ices-eg/SmartDots/files/2132583/SmartGG.docx)
New version with comments and additional text

**Comment by neil-ices-dk** [comment]
Have now clarified with the SCICOM chair and the EOSG chair: Smartdots will be formed as an expert group in the template we're developing. It will sit under the Ecosystem Observation Steering group

**Comment by JCoadDavies** [comment]
Super! Do we still need to invite the EOSG chair to be a member of the SSG or has this been done? 

The chairs of WGBIOP would like to suggest the following 8 members for the SSG:
- 1 member from each;  DTU (Julie), ILVO (?), IMR (Jane), IMARES (Cindy),
- 2 from ICES (Carlos and Sven)
- 1 from the Med (Maria Cristina Follesa - UNICA Italy), (need to check with her)
- 1 other with fresh eyes and possible link to assessment (Gráinne Ní Chonchúir - MI IRE), (need to check with her)
This gives 8 which is enough. Membership should be decided prior to WGBIOP.

**Comment by elstorreele** [comment]
Looks good to me, having Gráinne  on the SSG is a good suggestion. We'll have a chat internally at ILVO to stick a name to the ILVO member.

**Comment by neil-ices-dk** [comment]
Hi all, any conclusion on this - there is a package of EG's being prepared for approval at SCICOM, so now would be a good time to round this one off.

**Comment by elstorreele** [comment]
Dear All, Karen Bekaert will take up for ILVO. rgds Els

**Comment by neil-ices-dk** [comment]
ok that's good, thanks Els. As this will now follow the 'usual' procedure for WG establishment, i don't think you can name the participants pre-emptively as they need to be nominated to the group once established by the country delegates but the expected composition of the group is included in the 'participants' section - so we're covered.

@JCoadDavies as one of the proposed co-chairs of the group, are you prepared to finalise and submit the resolution to establish the group - note the name will be "WG Datras Governance"

**Comment by JCoadDavies** [comment]
OK. I take it you mean "WG SmartDots Governance". When is the deadline for submitting this? And when will the term begin, 2018?

In regards to Sven being a member. Has he been approached? 

And do the other confirmed (even if it is unofficially) members have any comments on the draft document as to what "type" of person should be co-chair?

**Comment by neil-ices-dk** [comment]
Indeed - cut and paste cock-up ;)

Deadline is more or less this week if we want to be in the good books of SCICOM

Sven is aware, and as the SGOM chair he is automatically in the loop, however it might still be a good idea to invite him as a member so he can actively contribute

**Comment by JCoadDavies** [comment]
Thanks Neil.
What the actual process for submitting, uploading, emailing...? we'll get it done this week :-)

**Comment by JCoadDavies** [comment]
Thanks Neil for putting me touch with the relevant people. 
As there have been no further suggestions and as we discussed and agreed upon in the last SmartDots meeting Jane will co-chair with me. The final draft is attached here. I will upload this to EOSG sharepoint on Thursday if there haven't been any objections here

[SmartGG_draft resolution.docx](https://github.com/ices-eg/SmartDots/files/2329595/SmartGG_draft.resolution.docx)

We have a core group of 6 participants and suggestions for 2 additional to invite. These have not been contacted yet and waiting until WGBIOP to do this is likely.

**Comment by JCoadDavies** [comment]
Neil, can you help again, please :-) 

Sorry, I'm not too au fait with github and now i see that we are only 4 assigned to this issue. Does that me we are the only ones seeing these comments. I was under the impression all of us SmartDotters we following this issue...?

**Comment by Osanna123** [comment]
Hi Julie,
I'm subscribed for the project, so i can see the comments. I hope, the same goes for Carlos...
Cheers,
Anna

**Comment by JCoadDavies** [comment]
Thanks for letting me know Anna.
I will send the SSG draft resolution to all of us in the SmartDotters group as suggested by Neil just to be sure everyone gets a copy.

**Comment by JCoadDavies** [comment]
[WGSMART ToRs 2018 - DRAFT.docx](https://github.com/ices-eg/SmartDots/files/2340091/WGSMART.ToRs.2018.-.DRAFT.docx)

 Final version uploaded to the EOSG Sharepoint

**Comment by neil-ices-dk** [comment]
well done 🥇
