### ISSUE TITLE
Sample is currently a number (long) in SmartDots software

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#72]
The Sample identifier is a number in the SmartDots software but it is a string.
The software need to be updated so that Sample changes to string in the software.

**Comment by ValerioVisconti** [comment]
Are we talking about this?
![file name issue](https://user-images.githubusercontent.com/43439015/45813231-f0d8f980-bcc9-11e8-99b0-5d022afa948d.jpg)

**Comment by kevinatilvo** [comment]
No, about the column to the right of it.
This issue has been fixed
