### ISSUE TITLE
Extract the list of events and readers of an event (overview)

### ISSUE THREAD

**Issue by elstorreele** [ices-eg/SmartDots#78]
It would be easier to have a list of the events and not only have to look/search for an event on the screen :).
Objective: have an overview to search in easy if an event was organised

**Comment by cmspinto** [comment]
Done, the user can now download the list of events: 

![image](https://user-images.githubusercontent.com/8705477/51119804-10b1a180-1814-11e9-90fc-e22bb52ce2eb.png)

**Comment by JCoadDavies** [comment]
We still need to be able to extract the list of readers of an event
