### ISSUE TITLE
Define and manage users

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#8]
- Manage users: add users, link users to a workshop, manage user expertise (per species,  per workshop?)
- via Active Directory
- refer to https://community.ices.dk/ExternalSites/arf/default.aspx

**Comment by cmspinto** [comment]
This is now done: http://smartdots.ices.dk/manage/UsersExpertise and event managers can add users to the event using a click or adding them by inserting their email or their username.
