### ISSUE TITLE
How do we deal with difficult otoliths and AQ scores? 

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#82]
Should all provide an age to all otoliths? Should we omit otoliths with AQ3? How many readers should consider it an AQ3 for it to be omitted?

Has   changed from priority 4 to 1 b. All analysis should exclude AQ3 readings   (there will be an option to include AQ3 in the analysis after issue 84   (software module) is implemented.

**Comment by JCoadDavies** [comment]
We have had requests from a workshop to include the AQ3 readings in the report. It is problematic that the AQ3 scores are excluded from the data output and report as it can potentially exclude a lot of readings, especially inexperienced readers.
How can we make it optional to have them included or excluded?

**Comment by JCoadDavies** [comment]
On 28/02/19
Carlos made it optional the inclusion of AQ3 records in the download and report. 
That means that the even manager can choose if he wants to include or not  the AQ3 in the download and report (by default the AQ3 annotation won’t be in the report).

**Comment by cmspinto** [comment]
Report:

the download changed, from today (25/09/2019) the readings include only the AQ1, AQ2 (like it was before) but in case the user has enable the option “Include AQ3” then the download will also have AQ3_QA.

The difference is that before it had all the readings  (it consider the readings without AQ an AQ3 reading). 
Now with the new AQ’s it is not possible anymore!
