### ISSUE TITLE
Overview of readers progress required

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#83]

**Comment by JCoadDavies** [comment]
- No   extra functionality needed in SmartDots software. All wishes can be   implemented through an expansion of the Web API.     - The sample state shown as a colour in the file list can be used to   indicate the progress of the agereader.    (eg. green = approved annotation ; red = todo ; orange = at least on   annotation )     - The number of finished agereadings relative to the total number of   otoliths  can be shown in a extra   column in the activity/event screen.
--

**Comment by wimallegaert** [comment]
The information about the progress can be integrated in the activity screen. The activity list is generic, the content is defined by the Web API. An extra column can be added (eg. count open/count total). 

The image below shows how this was implemented at ILVO.
![image](https://user-images.githubusercontent.com/13795097/56737756-6e3a8000-676b-11e9-8317-f0cfb375ed39.png)

**Comment by cmspinto** [comment]
Done, 
it count the number of samples and the number of annotations

![image](https://user-images.githubusercontent.com/8705477/64700864-fd8cc980-d4a7-11e9-8fe7-c7c6126eaa4b.png)

**Comment by cmspinto** [comment]
It will be published when the new WebAPI is published
