### ISSUE TITLE
AQ3 - no age to be added to readability scale

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#84]
Given   that age class 0 appears by default in the readings, there is no way to   differentiate when considering an illegible otolith (which should be left   blank) from an otolith age class 0 with little security (AQ3). It should be   possible to select another AQ- "illegible" that left the Age field   blank.

**Comment by JCoadDavies** [comment]
Comment from ILVO at WGSMART WK 
AQ   vocabulary is loaded into SmartDots via a specific Web API method   (getreadabilityqualities)     + A new value "AQ3 - age not provided" will be added in the ICES   vocab        - Code: AQ3-NoAge        - Description: AQ3 - age not   provided     + Custom business logic will be developed in SmartDots based on the new   value (=AQ3-NoAge). If AQ =    "AQ3-NoAge" then        - Age will be set to NULL in user   interface        - The property "Result"   in the DTO object Annotation will be set to NULL        - All placed dots will be removed
--

**Comment by JCoadDavies** [comment]
Once this has been completed issue 82 needs to be answered "All analysis should exclude AQ3 readings (there will be an option to include AQ3 in the analysis after issue 84 (software module) is implemented."

**Comment by wimallegaert** [comment]
The following was agreed on WGSMART Meeting April 25th:
- The value "AQ3-NoAge" will be "hard-coded" added to the AQ vocabulary
- The registration of the AQ code will be mandatory. Current functionality: when you select a new sample after annotating, the annotation popup opens automatically but you can close this popup without entering an AQ code. In the new version the registration of an AQ code will be required for all annotations.

**Comment by kevinatilvo** [comment]
An extra AQ-code “AQ3-NoAge” can be added via the Web API. 
 
![image](https://user-images.githubusercontent.com/25780423/57923524-d419b380-78a2-11e9-9322-cda3e4d8068f.png)

When “AQ3-NoAge” is selected, all dots will be erased from the annotation (if there are any) and the Age field will become empty.

**Note**: Currently it is NOT possible to enforce the user to fill in an AQ-code, because there are too many ways a user can skip on this, and because it would heavily affect existing web api’s to implement the feature, this request could therefore not be completed.

**Comment by wimallegaert** [comment]
The new value AQ3-NoAge could be in conflict with the existing Ices vocab: https://vocab.ices.dk/?ref=1395 (TS_OtGrading - Otolith reading quality grading). 
AQ3	= Rings can not be counted, the otolith is unreadable. What is the difference with AQ3-NoAge?Feedback needed.

**Comment by JCoadDavies** [comment]
I think we should at all costs avoid conflicting with the ICES vocab as this is potentially used across ICES databases (at least for now).
I think the problem is that age class 0 appears by default in the readings (see first comment on this issue). Can the default be NA and if the age is 0 then it needs to be inserted as 0? 
Then we need to decide if a reader should provide and age or not when they see the otolith as being: AQ3- Rings can not be counted, the otolith is unreadable (as in vocab)
(probably, yes they should)

Relevant to this and linking to #82 see the new CRR document, section 6.1.1 referring to AQ scores (https://www.ices.dk/news-and-events/news-archive/news/Pages/New-handbook-on-fish-age-estimation.aspx)  :-)

Maybe what we need in the report is some sort of quantification of the number of AQ3's....?
