### ISSUE TITLE
Option to show/hide biological parameters in the software

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#85]
The   coordinator should be allowed to choose to show/hide which biological   parameter data appears in the software.
--

**Comment by JCoadDavies** [comment]
Should be done in the edit event page, an option to hide for e.g fish length and weight

**Comment by cmspinto** [comment]
This option was implemented, 
The steps were: 

Add the option in the edit event page to show or hide the biological parameters: 
![image](https://user-images.githubusercontent.com/8705477/65674248-8846fa00-e04c-11e9-92a2-4d2b71914d65.png)

This enables the user to hide the biological parameters. 
In the software it will appear "NA" when this option is enabled: 

![image](https://user-images.githubusercontent.com/8705477/65674399-c5ab8780-e04c-11e9-9b60-029e2b43aa84.png)


Note: After the event is closed then the biological parameters are again displayed!
