### ISSUE TITLE
Blind reading functionality

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/SmartDots#9]
Develop extra functionality: only  the  administrator  should  have  access  to  all age-readings during a calibration exercise. The age-readers can only see their own readings. 
Once the status of a workshop is completed age-readers can also check the data of other readers.

Integration in functionality (security role): 
- Depending on user-role show own age readings or all age readings. 
- Depending on workshop status

There are only 2 levels; **Managers and Users (in workshop)**

**Comment by wimallegaert** [comment]
Specified business logic should be integrated in Web API
