### ISSUE TITLE
Make SmartDots video tutorials

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#90]

**Comment by JCoadDavies** [comment]
new points added to the recording software tools.dox
[Recording.software.tools.docx](https://github.com/ices-eg/SmartDots/files/3718785/Recording.software.tools.docx)

**Comment by JCoadDavies** [comment]
wim has made some videos for the software and julie to make a voice over for 1 video and send to WIm for him to test combining the video and voice in week beginning 25th Nov

**Comment by kbekaert** [comment]
Audio available for 4 more videos. Joana can finish those. More audio is needed for WebApi and SmartDots software.

**Comment by JCoadDavies** [comment]
[SmartDots Video Tutorial Overview.xlsx](https://github.com/ices-eg/SmartDots/files/4286856/SmartDots.Video.Tutorial.Overview.xlsx)
 
Attached file gives a progress status overview

**Comment by JaneGodiksen** [comment]
Julie will do this during the first week of June
