### ISSUE TITLE
Hide reading line functionality

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#92]
Needed for comparison of results of readers.
Comment from ILVO at WGSMART WK...
"+ A ""Hide reading line"" checkbox will be integrated in the image toolbar
+  If the reading line option is set to hidden, all functionalities will work as usual:
   - The user can add dots, the dots will be placed on (the invisible) line.
   - The user can  use the zoom in and zoom out functionalities
   - The user can select other files or annotations
+ If the line button is activated in the toolbar, the line will always be shown (to checkbox will be always unchecked)"

**Comment by kevinatilvo** [comment]
There is a new toggle button was added in the age-reading window.  Clicking on this button toggles the line visibility:  
![image](https://user-images.githubusercontent.com/25780423/57923628-1e9b3000-78a3-11e9-9e87-c1729127d550.png)
![image](https://user-images.githubusercontent.com/25780423/57923639-24911100-78a3-11e9-9988-99e4fec54e44.png)
![image](https://user-images.githubusercontent.com/25780423/57923644-28bd2e80-78a3-11e9-8da4-e4d3e75d196e.png)
When the line is invisible, dots can still be added. 
The button also toggles on-screen measurings (See issue 111).

**Comment by JCoadDavies** [comment]
Technically still in testing, we wait and close this once the new release happens
