### ISSUE TITLE
Copy token with one click

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#95]
A copy token botton. No need to mark the tokten to copy it.

**Comment by cmspinto** [comment]
This is change now! 
The user can use the button to copy the token to the clipboard:

![image](https://user-images.githubusercontent.com/8705477/81746668-3225aa80-94a7-11ea-9c0d-fddd6b70b8c1.png)


If the user has no valit token a warning will appear!

**Comment by JCoadDavies** [comment]
Thanks Carlos. It works.
I think the message should say "you can now **paste** the token **into** the smartdots software **login screen**"
