### ISSUE TITLE
Agreed birthday visual

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#96]
Include in the viewer the agreed birth date for the species so that readers do not depend on "memory"; for example, next to the capture date  in the sample part.

Be able to change the birthday date in the software. Currently SmartDots automatically give the age of the fish based on the number of ring annotations that you make, this implies that SmartDots already has a pre-established birthday date (1st of January). This has been a problem in the case of the anchovy from Mediterranean area  (birthday on 1st of July) and it was necessary to leave the last winter ring unmarked so that the automatic age determination agreed with the one corresponding with birthday date on July 1. This implied that for otoliths from the first half of the year it was not possible to compare the position of the winter rings which were not annotated with other area results. THIS IS SOFTWARE, WEBAPI and REPORTING

A read-only view of the birthday is already possible,properties can be dynamicly  added the to sample frame.

See ID 50. Maybe it's also an option tro use the incomplete feature here?

**Comment by JaneGodiksen** [comment]
#121 will solve the problem

**Comment by JaneGodiksen** [comment]
Clear instructions needs to be given to the readers as well.

**Comment by JCoadDavies** [comment]
Clear instructions in the manual and this point will be included in the newsletter
